import Location from "../models/location.model.js";

async function seedLocations() {
	const count = await Location.countDocuments();
	if (count !== 0) return;

	const districts = [
		{
			districtEn: "Akkar",
			districtAr: "عكار",
			citiesEn: [
				"Aadouiye",
				"Aaidamoun",
				"Aaiyat",
				"Aakkar El Attiqa",
				"Aamara",
				"Aaouinat",
				"Aarab Jourmnaya",
				"Aarida",
				"Aarmeh",
				"Aarqa",
				"Aayoun",
				"Aayoun El Ghezlane",
				"Abde",
				"Ain er Rsas",
				"Ain ez Zeit",
				"Ain Faouar",
				"Ain Tinta",
				"Ain Yaaqoub",
				"Akroum",
				"Al-Massoudieh",
				"Amaret el Baykat",
				"Amayer",
				"Andqat",
				"Ard es Soud",
				"Awade",
				"Baaliye",
				"Baddouaa",
				"Bajaa",
				"Balde",
				"Bani Sakher",
				"Barcha",
				"Bebnine",
				"Beino",
				"Beit Ali Adraa",
				"Beit Ayoub",
				"Beit Daoud",
				"Beit el Haj",
				"Beit el Haouch",
				"Beit Ghattas",
				"Beit Khlaiyel",
				"Beit Mellat",
				"Beit Younes",
				"Bellanet el Hissa",
				"Berbara",
				"Berqayel",
				"Bezbina",
				"Bire Akkar",
				"Borj el Arab",
				"Boustane El Herch",
				"Bqayaa",
				"Bqerzala",
				"Bzaita",
				"Bzal",
				"Chadra",
				"Chane",
				"Chaqdouf",
				"Charbila",
				"Chattaha",
				"Cheik Mohammad",
				"Cheikh Aayash",
				"Cheikh Hmairine",
				"Cheikh Taba",
				"Cheikh Taba es Sahl",
				"Cheikh Zennad Talbibe",
				"Cheikhlar",
				"Chir Hmairine",
				"Dabadeb",
				"Daghle",
				"Dahr Aayas",
				"Dahr El Ballane",
				"Dahr el Houssain",
				"Dahr Laissineh",
				"Danke et El Amriyeh",
				"Daousse Baghdadi",
				"Darine",
				"Dayret Nahr el Kabir",
				"Deir Dalloum",
				"Deir Janine",
				"Deir Mar Jeryos",
				"Denke",
				"Dibbabiye",
				"Dinbou Ain al zahab",
				"Doueir Aadouiye",
				"Ech Cheikh Maarouf",
				"Ed Daoura",
				"Ed Daousse",
				"Ed Debbabiye el Charqiye",
				"Ed Debbabiye el Gharbiye",
				"El Aabboudiye",
				"El Aamriye",
				"El Aaouaichat",
				"El Aarida",
				"El Aayoun",
				"El Barde",
				"El Borj Akkar",
				"El Fraidis",
				"El Ghawaya",
				"El Haissa",
				"El Hichi",
				"El Houaich",
				"El Kharnoubeh",
				"El Khirbe",
				"El Khirbe Msalla",
				"EL Khirbe Qleiaat",
				"El Khoder",
				"El Kneisse",
				"El Kouraniye",
				"El Krahne",
				"El Kroum",
				"El Majdal",
				"El Majdel",
				"El Mbar kiye",
				"El Melkiye",
				"El Mqaiteaa",
				"El Qantara",
				"El Qatlabe",
				"El Qlaiaat",
				"El Qorne",
				"El Qsair",
				"El Rama",
				"En Nabi Khaled",
				"Er Ransiye",
				"Er Rouaime",
				"Es Sayeh",
				"Es Souaisse",
				"Ez Zouq",
				"Fard",
				"Fnaideq",
				"Fsiqine et Ain Echma",
				"Ghzaile",
				"Habchit",
				"Haider",
				"Haitla",
				"Haizouq",
				"Halba",
				"Haouch",
				"Haouchab",
				"Haret Beit Kessab",
				"Haret ej Jdide",
				"Haret ej Jdide Mqaiteaa",
				"Hedd",
				"Hikr Janine",
				"Hissa",
				"Hmaireh Aakkar",
				"Hmais",
				"Hnaider",
				"Hokr ech Cheikh Taba",
				"Hokr ed Dahri",
				"Hokr el Kousse",
				"Hokr El Mahmoudiye",
				"Hokr Etti",
				"Hokr Jouret Srar",
				"Hrar",
				"Idbil",
				"Ilat",
				"Janine",
				"Jdaidet Ej Joumeh",
				"Jdeide",
				"Jdeidet El Qaitaa",
				"Jebrayel",
				"Jichet Aali Houssein",
				"Jouret Srar",
				"Kafr El Ftouh",
				"Kafroun",
				"Kalkha",
				"Karm el Aasfour",
				"Karm Zebdine",
				"Kawashra",
				"Kfar Harra",
				"Kfar Melki",
				"Kfar Noun",
				"Kfartoun",
				"Khalsa",
				"Khane Hayat",
				"Khat Petrol",
				"Khirbet Char",
				"Khirbet Daoud",
				"Khirbet er Roummane",
				"Khirbit Ej Jord",
				"Khorab el Haiyat",
				"Khraibe Akkar",
				"Khreibet ej Jindi",
				"Knaisse Hnaider",
				"Knisseh",
				"Kouikhat",
				"Kousha",
				"Kroum el Arab",
				"Machha",
				"Machta Hammoud",
				"Machta Hassan",
				"Mahmoudiye",
				"Majdla",
				"Mar Lia Hdare",
				"Mar Sahllita",
				"Mar Touma",
				"Marlayet Haddara",
				"Marlayet Melhem",
				"Martmoura",
				"Mazraat Al Balde",
				"Mechaeilha Hakour",
				"Mechmech",
				"Meghraq",
				"Meghraqa",
				"Memnaa",
				"Mhamra",
				"Mhatat Siket el Hadid",
				"Minyara",
				"Mouanse",
				"Mounjez",
				"Mqaible",
				"Mqaitaa",
				"Mrah Aakkar",
				"Mrah Al Khawkh",
				"Mrah el Aainouni",
				"Mrah el Bsatine",
				"Mrah Qamar ed Dine",
				"Msalla",
				"Mzeihmeh",
				"Nabaa el Ghzaile",
				"Nahr El Bared",
				"Nahriye",
				"Nassriye",
				"Nfaisseh",
				"Noura",
				"Noura el Faouqa et el Tahta",
				"Noura el Tahta",
				"Ouadi Ej jamous",
				"Qaabrine",
				"Qabaait",
				"Qanbar",
				"Qarha Akkar",
				"Qarqaf",
				"Qbaiyat el Gharbiye",
				"Qbaiyat ez Zouq",
				"Qboula",
				"Qbour El Bid",
				"Qinye",
				"Qloud El-Baqieh",
				"Qochloq",
				"Qoubaiyat",
				"Qoubbet Chamra",
				"Qraiyat",
				"Rahbe",
				"Rajm Hssein",
				"Rajm Issa",
				"Rajm Khalaf",
				"Rihaniye",
				"Rmah En Nahriyeh",
				"Rmoul",
				"Saadine",
				"Sadaqa",
				"Sahle",
				"Saidnaya",
				"Saissouq",
				"Sammouniye",
				"Saoualha",
				"Sbagha",
				"Semmaqiye",
				"Semmaqli",
				"Sfaynet El-Qaitaa",
				"Sfinet ed Dreib",
				"Shaqdouf Aakkar",
				"Sindianet Zeidane",
				"Srar",
				"Takrit",
				"Tal Meaayan",
				"Tall Aabbas Ech-Charqi",
				"Tall Aabbas el Gharbi",
				"Tall Bire",
				"Tall Hmayra",
				"Tallet el Mjabber",
				"Tallet ez Zefir",
				"Tashea",
				"Tell Bibi",
				"Tell Hayat",
				"Tell Kindi",
				"Tell Kiri",
				"Tell Sebael",
				"Tleil",
				"Wadi Al Hoor",
				"Wadi Khaled",
				"Zouaitini Akkar",
				"Zouarib",
				"Zouk Haddara",
				"Zouq el Hassineh",
				"Zouq El Mqachrine",
				"Zouq El-Hbalsa",
			],
			citiesAr: [
				"عدوي",
				"عيدمون",
				"عيات",
				"عكار العتيقة",
				"عماره",
				"العوينات",
				"جرمنايا",
				"عريضا",
				"عرمه",
				"عرقا",
				"عيون",
				"عيون الغزلان",
				"العبده",
				"عين الراس",
				"عين الزيت",
				"عين الفوار",
				"عين تنتا",
				"عين يعقوب",
				"اكروم",
				"المسعودية",
				"عمار البيكات",
				"العماير",
				"عندقت",
				"ارض السود",
				"العواده",
				"بعليا",
				"بدويا",
				"بجعة",
				"بلدي",
				"بني صخر",
				"برشا",
				"ببنين",
				"بينو",
				"بيت علي عدرة",
				"بيت ايوب",
				"بيت داوود",
				"بيت الحاج",
				"بيت الحوش",
				"بيت غطاس",
				"بيت خلايل",
				"بيت ملات",
				"بيت يونس",
				"بلانة الحيصة",
				"برباره",
				"برقايل",
				"بزبينا",
				"البيره عكار",
				"برج العرب",
				"بستان الحرش",
				"البقيعه",
				"بقرزلا",
				"بزيتا",
				"بزال",
				"شدره",
				"شان",
				"الشقدوف",
				"شربيلا",
				"شطاحة",
				"الشيخ محمد",
				"الشيخ عياش",
				"شيخ حمارين",
				"الشيخ طابا",
				"الشيخ طابا السهل",
				"الشيخ زناد",
				"شيخلار",
				"شير حمارين",
				"داباديب",
				"الدغلة",
				"ضهر عياس",
				"ضهر البلانه",
				"ضهر الحسين",
				"ضهر ليسينه",
				"دنكة و العامرية",
				"دوسة بغدادي",
				"دارين",
				"دائرة النهر الكبير",
				"دير دلوم",
				"دير جنين",
				"دير مار جريس",
				"دنكي",
				"دبابية",
				"دنبو عين الذهب",
				"دوير عدويه",
				"الشيخ معروف",
				"الدوره",
				"الدوسة",
				"الدبابية الشرقية",
				"الدبابية الغربية",
				"العبودية",
				"العمارية",
				"العويشات",
				"العريضة",
				"العيون",
				"بردي",
				"البرج عكار",
				"فريديس",
				"القبيات غوايا",
				"الحيصة",
				"الهيشه",
				"الحويش",
				"الخرنوبه",
				"الخربة",
				"الخربة مصلا",
				"الخربة قليعات",
				"الخضر اكروم",
				"الكنيسة",
				"الكورانية",
				"الكراهنة",
				"الكروم",
				"المجدل العماير",
				"المجدل عكار",
				"المباركية",
				"الملكي",
				"المقيطع",
				"القنطرة",
				"القبيات القطلبه",
				"القليعات",
				"القرنة",
				"القصير",
				"الرامه",
				"النبي خالد",
				"الرانسية",
				"الرويمة",
				"السايح",
				"السويسة",
				"الذوق",
				"الفرض",
				"فنيدق",
				"فسقين و عين اشما",
				"الغزيله",
				"حبشيت",
				"حيدر",
				"هيتلا",
				"حيزوق",
				"حلبا",
				"حوش",
				"هوشب",
				"حارة بيت كساب",
				"حارة الجديدة",
				"حارة الجديدة المقيطع",
				"الهد",
				"حكر جنين",
				"الحيصا",
				"الحميرة",
				"حميص",
				"حنيدر",
				"حكر الشيخ طابا",
				"حكر الضاهري",
				"حكر الكوسا",
				"حكر المحمودية",
				"حكر قتة",
				"حكر جورة سرار",
				"حرار",
				"عدبل",
				"ايلات",
				"جنين",
				"جديدة الجومه",
				"جديدة",
				"جديدة القيطع",
				"جبرائيل",
				"جيشة علي حسين",
				"جورة سرار",
				"كفر الفتوح",
				"كفرون",
				"كلخا",
				"كرم عصفور",
				"كرم زبدين",
				"الكواشرة",
				"كفرحره",
				"كفرملكي",
				"كفرنون",
				"كفرتون",
				"خالصة",
				"خان الحيات",
				"خط البترول",
				"خربة شار",
				"خربة داوود",
				"خربة الرمان",
				"خربة الجرد",
				"خرب الحيات",
				"الخريبة",
				"خريبة الجندي",
				"كنيسة هنيدر",
				"كنيسة",
				"الكويخات",
				"كوشا",
				"كروم العرب",
				"مشحة",
				"مشتى حمود",
				"مشتى حسن",
				"المحمودية",
				"مجدلا",
				"مار ليا حدار",
				"مار شليطا",
				"مار توما",
				"مارليات حدارا",
				"مار ليا ملحم",
				"القبيات مرتموره",
				"مزرعة بلدة",
				"مشيلحة الحاكور",
				"مشمش",
				"المغراق",
				"مغراقا",
				"ممنع",
				"المحمرة",
				"محطة سكة الحديد",
				"منيارة",
				"المونسه",
				"منجز",
				"المقيبلة",
				"مقيطع السماكلي",
				"مراه عكار",
				"مراح الخوخ",
				"مراه العينوني",
				"مراح البساتين",
				"مراح قمر الدين",
				"مصلا",
				"مزيحمة",
				"نبع الغزيلة",
				"نهر البارد",
				"النهريه",
				"ناصرية",
				"النفيسة",
				"النوره",
				"نورا الفوقا و التحتى",
				"نورا التحتا",
				"وادي الجاموس",
				"قعبرين",
				"قبعيت",
				"القنبر",
				"قرحه عكار",
				"القرقف",
				"القبيات الغربية",
				"القبيات الذوق",
				"قبولا",
				"قبور البيد",
				"قنية",
				"قلود الباقية",
				"قشلق",
				"القبيات",
				"قبة شمرا",
				"القريات",
				"رحبة",
				"رجم حسين",
				"رجم عيسى",
				"رجم خلف",
				"الريحانية",
				"رماح النهريه",
				"رمول",
				"سعدين",
				"صدقة",
				"السهله",
				"السنديانة",
				"سيسوق",
				"السمونيه",
				"ساولها",
				"صباغا",
				"السماقية",
				"سمقالي",
				"سفينة القيطع",
				"سفينة الدريب",
				"شقدوف عكار",
				"سنديانة زيدان",
				"سرار",
				"تكريت",
				"تلمعيان",
				"تل عباس الشرقي",
				"تلعباس غربي",
				"تلبيرة",
				"تلحميرة",
				"تلة المجابر",
				"تلة الزفير",
				"تاشع",
				"تلبيبة",
				"تل الحيات",
				"تل كندي",
				"تل كيري",
				"تل سبعل",
				"التليل",
				"وادي الحور",
				"وادي خالد",
				"الزويتينة عكار",
				"الزواريب",
				"ذوق حدارة",
				"ذوق الحصينة",
				"ذوق المقشرين",
				"ذوق الحبالصة",
			],
		},
		{
			districtEn: "Beirut",
			districtAr: "بيروت",
			citiesEn: [
				"Aadlyeh",
				"Achrafiye",
				"Ain El Tine",
				"Ain Mreisse",
				"Al Hikmat",
				"Bab Idriss",
				"Bachoura",
				"Basta Faouka",
				"Basta Tahta",
				"Beirut",
				"Beirut Central District",
				"Bourj Abi Haidar",
				"Champ de courses",
				"Corniche El Naher",
				"Dar Al Fatwa",
				"Ej Jeitaoui",
				"El Aamliye",
				"El Ghabe",
				"El Hamra",
				"El Horge",
				"El Majidiye Beirut",
				"El Manara",
				"El Wata",
				"El Zarif",
				"Fourn el Hayek",
				"Gemmayze",
				"Grand Serail",
				"Hotel Dieu",
				"Jamia",
				"Jisr",
				"Jounblat",
				"Khodr",
				"La Sagesse",
				"Malaab",
				"Manara",
				"Mar Elias",
				"Mar Maroun",
				"Mar Mitr",
				"Mar Mkhayel",
				"Mar Nqoula",
				"Marfaa",
				"Mazraa",
				"Medouar",
				"Minet el Hosn",
				"Moussaitbe",
				"Moustachfa er Roum",
				"Najmeh",
				"Nasra",
				"Palais De Justice",
				"Parc",
				"Patriarcat",
				"Place de l'Etoile",
				"Qantari",
				"Qobaiyat",
				"Qoraitem",
				"Ramlet el Bayda",
				"Raoucheh",
				"Ras Beirut",
				"Ras El Nabaa",
				"Remeil",
				"Saife",
				"Sanayeh",
				"Sioufi",
				"Snoubra",
				"Tallet Druze",
				"Tallet el Khayat",
				"Tariq El Jdide",
				"Unesco",
				"Universite Americaine",
				"Universite St Joseph",
				"Zoqaq el Blat",
			],
			citiesAr: [
				"العدلية",
				"الاشرفية",
				"عين التينة",
				"عين المريسه",
				"حكمة",
				"باب إدريس",
				"باشورة",
				"بسطا الفوقا",
				"بسطا التحتا",
				"بيروت",
				"وسط بيروت",
				"برج أبو حيدر",
				"ميدان سباق الخيل",
				"كورنيش النهر",
				"دارالفتوى",
				"جعيتاوي",
				"عاملية",
				"غابي",
				"حمرا",
				"حرش",
				"مجيدية (بيروت)",
				"منارة",
				"الوطى",
				"ظريف",
				"فرن الحايك",
				"جميزة",
				"سراي الكبير",
				"اوتيل ديو",
				"الجامعة",
				"جسر",
				"جنبلاط",
				"الخضر",
				"الحكمة",
				"ملعب",
				"المنارة",
				"مار الياس",
				"مار مارون",
				"مار متر",
				"مار مخايل",
				"مار نقولا",
				"مرفأ",
				"المزرعة",
				"مدور",
				"مينا الحصن",
				"مصيطبة",
				"مستشفى الروم",
				"النجمة",
				"الناصرة",
				"قصر العدل",
				"سباق الخيل",
				"بطركية",
				"ساحة النجمة",
				"قنطاري",
				"قبيات",
				"قريطم",
				"الرملة البيضا",
				"روشه",
				"راس بيروت",
				"راس النبع",
				"رميل",
				"صيفي",
				"الصنائع",
				"السيوفي",
				"صنوبره",
				"تلة الدروز",
				"تلة الخياط",
				"طريق الجديدة",
				"الاونسكو",
				"الجامعة الاميركية",
				"جامعة القديس يوسف",
				"زقاق البلاط",
			],
		},
		{
			districtEn: "Mount Lebanon - Baabda",
			districtAr: "جبل لبنان - بعبدا",
			citiesEn: [
				"Aabadiye",
				"Aarbaniye",
				"Abbdiyeh al Jadideh",
				"Ain er Roummane",
				"Ain es Sihha",
				"Ain Mouaffaq",
				"Arayia",
				"Arsoun",
				"Baabda",
				"Baajour",
				"Baalchmay",
				"Baalchmay ej Jdide",
				"Bhala",
				"Bir el AAbed",
				"Bir Hassan",
				"Bmariam",
				"Borj el Brajne",
				"Boutchai",
				"Brazilia",
				"Bsaba & Ouadi Dlab",
				"Btaaline",
				"Btebyat",
				"Btekhnay",
				"Bzebdine",
				"Chatila",
				"Chbaniye",
				"Chiayah",
				"Chmaissa",
				"Chouit",
				"Cite Sportive",
				"Dahr el Baidar",
				"Deir el Harf",
				"Deir Khouna",
				"Deir Mar Elias",
				"Deir Mar Youhanna",
				"Deir Saiya",
				"Dhour Al Aabaydiyeh",
				"Dlaibe",
				"El Baqle",
				"El Maadan",
				"El Marmah",
				"El Mdaoura",
				"El Ouzaai",
				"Er Rihaniye",
				"Er Rouais",
				"Es Sheime",
				"Et Tahouita",
				"Ez Zire",
				"Faiyadiye",
				"Falougha",
				"Fsakin",
				"Furn ech Chebak",
				"Ghobeire",
				"Hadet",
				"Hammana",
				"Haql Hassan",
				"Haret El Botm",
				"Haret el Mjadle",
				"Haret er Roum",
				"Haret es Set",
				"Haret Hamze",
				"Haret Hraik",
				"Hasbaiya el Metn",
				"Hazmiye",
				"Hlaliye",
				"Jamhour",
				"Jnah",
				"Jouar el Haouz",
				"Jouret Arsoun",
				"Kahlouniye",
				"Kfar Selouane",
				"Kfarchima",
				"Khalouat",
				"Khraibe Baabda",
				"Knisse",
				"Lailake",
				"Louaize",
				"Mar Taqla",
				"Mazzraat Maaissra",
				"Mdeyrej",
				"Merdache",
				"Mraije",
				"Mzayraa",
				"Ouadi Chahrour el Olia",
				"Ouadi Chahrour el Soufla",
				"Qalaa",
				"Qirtada",
				"Qornayel",
				"Qoubbeiaa",
				"Qraiye",
				"Qsaibe",
				"Qtale",
				"Ras el Harf",
				"Ras el Metn",
				"Rouaisset Salima",
				"Rouisset el Ballout",
				"Sabra",
				"Salima Baabda",
				"Saqi Ain el Hadath",
				"Sibnay",
				"Tahouitet el Ghadir",
				"Tarchich",
				"Warware",
				"Yarzeh",
				"Zandouqa",
				"Zouaitini",
			],
			citiesAr: [
				"عبادية",
				"عربانية",
				"عبادية الجديدة",
				"عين الرمانة بعبدا",
				"عين الصحة",
				"عين موفق",
				"عاريا",
				"ارصون",
				"بعبدا",
				"بعجور",
				"بعلشميه",
				"بعلشميه الجديدة",
				"بحالا",
				"بئر العبد",
				"بئر حسن",
				"بمريم",
				"برج البراجنة",
				"بطشيه",
				"برازيليا",
				"بسابا وادي الدلب",
				"بتعلين",
				"بتبيات",
				"بتخناي",
				"بزبدين",
				"شاتيلا",
				"شبانية",
				"شياح",
				"شميسة",
				"شويت",
				"المدينة الرياضية",
				"ضهر البيدر",
				"دير الحرف",
				"دير خونة",
				"دير مار الياس",
				"دير مار يوحنا",
				"دير سيا",
				"ضهور العبادية",
				"دليبه",
				"بقلة",
				"المعادن",
				"مرمح",
				"مدورا",
				"اوزاعي",
				"ريحانية",
				"الرويس",
				"الشيمة",
				"التحويطة",
				"زيره",
				"فياضية",
				"فالوغا",
				"فساقين ترشيش",
				"فرن الشباك",
				"غبيري",
				"حدث",
				"حمانا",
				"حقل حسن",
				"حارة البطم",
				"حارة المجادلة",
				"حارة الروم",
				"حارة الست",
				"حارة حمزة",
				"حارة حريك",
				"حاصبيّا المتن",
				"حازمية",
				"هلالية",
				"جمهور",
				"جناح",
				"جوار الحوز",
				"جورة ارصون",
				"كحلونية",
				"كفرسلوان",
				"كفرشيما",
				"خلوات",
				"خريبة بعبدا",
				"كنيسة بعبدا",
				"ليلكي",
				"لويزة",
				"مار تقلا",
				"مزرعة المعيصرة",
				"مديرج",
				"مرداشة",
				"مريجة",
				"مزيرعة بعبدا",
				"وادي شحرور العليا",
				"وادي شحرور السفلى",
				"القلعة",
				"قرطادة",
				"قرنايل",
				"قبيع",
				"قرية",
				"قصيبة",
				"قتالة",
				"راس الحرف",
				"راس المتن",
				"رويسات صليما",
				"رويسة البلوط",
				"صبرا",
				"صليما بعبدا",
				"سقي عين الحدث",
				"سبنيه",
				"تحويطة الغدير",
				"ترشيش",
				"الوروار",
				"اليرزة",
				"زندوقة",
				"زويتينة",
			],
		},
		{
			districtEn: "Mount Lebanon - Aley",
			districtAr: "جبل لبنان - عاليه",
			citiesEn: [
				"Aabey",
				"Aaley ej Jdide",
				"Aamroussieh Choueifat",
				"Aaramoun",
				"Aazzouniye",
				"Ain Al Saydeh",
				"Ain Anoub",
				"Ain Dara",
				"Ain Drafil",
				"Ain ej Jdide",
				"Ain el Fraidis",
				"Ain el Halzoun",
				"Ain el Jaouze",
				"Ain el Marj",
				"Ain er Remmane",
				"Ain Hala",
				"Ain Ksour",
				"Ain Trez",
				"Ainab",
				"Aitat",
				"Aley",
				"Baaouerta",
				"Baissour",
				"Bchamoun",
				"Bdedoun",
				"Bedghane",
				"Bhamdoun ed Dayaa",
				"Bhamdoun el Mhatta",
				"Bhouara",
				"Bihat",
				"Bkhechtay",
				"Blaibel",
				"Bmahray",
				"Bmekkine",
				"Bnaiye",
				"Botros",
				"Bou Zraid",
				"Bou Zraide",
				"Bourdine",
				"Bsatine",
				"Bserrine",
				"Bsous",
				"Btalloun",
				"Btater",
				"Chamlikh",
				"Chanay",
				"Charoun",
				"Chartoun",
				"Chemlane",
				"Chqif Btalloun",
				"Dahr El Ouahch",
				"Daqqoun",
				"Deir Qoubil",
				"Dfoun",
				"Doueir er Remmane",
				"El Blat",
				"El Ftaihat",
				"El Ouata",
				"En Njassa",
				"Es Shwayfate",
				"Fsaqine",
				"Ghaboun",
				"Ghadir",
				"Habramoun",
				"Haret Chbib",
				"Haret el Mir",
				"Haret Salem",
				"Hay el Aarab",
				"Hay es Sellom",
				"Hay es Sindiane",
				"Homs Oua Hama",
				"Houmal",
				"Ighmid",
				"Jabal El Aarid",
				"Jisr el Qadi",
				"Kahale",
				"Kaifoun",
				"Kfar Aamaiy",
				"Kfar Matta",
				"Khalde",
				"Kliliye",
				"Maaroufiye",
				"Maasraiti",
				"Majdalaya",
				"Mansouriye bhamdoun",
				"Mantra",
				"Marj Chartoun",
				"Mazraat el Boueit",
				"Mazraat en Nahr",
				"Mechakhti",
				"Mechrefe",
				"Mejdel Baana",
				"Mounsa Aaley",
				"Mreijat Aley",
				"Oumara Choueifat",
				"Qabr Chamoun",
				"Qmatiye",
				"Qoubbe Choueifat",
				"Ram Bchamoun",
				"Ramliye",
				"Rechmaiya",
				"Rejme",
				"Remhala",
				"Rjoum",
				"Rouissat Sofar",
				"Rouisset en Naamane",
				"Sarahmoul",
				"Sibaal",
				"Sil",
				"Silfaya",
				"Sofar",
				"Souq el Gharb",
				"Taazniye",
				"Touayte Ain Dara",
				"Watiye",
				"Yinnar",
			],
			citiesAr: [
				"عبيه",
				"عاليه الجديدة",
				"عمروسية الشويفات",
				"عرمون",
				"العزونيه",
				"عين السيدة",
				"عين عنوب",
				"عين داره",
				"عين درافيل",
				"عين الجديدة",
				"عين الفريديس",
				"عين الحلزون",
				"عين الجوزه",
				"عين المرج",
				"عين الرمانة",
				"عين حالا",
				"عين كسور",
				"عين تراز",
				"عيناب",
				"عيتات",
				"عاليه",
				"بعورته",
				"بيصور",
				"بشامون",
				"بدادون",
				"بدغان",
				"بحمدون الضيعة",
				"بحمدون المحطة",
				"بحوارا",
				"بهات",
				"بخشتيه",
				"بليبل",
				"بمهريه",
				"بمكين",
				"البينه",
				"بطرس",
				"بو زريدة",
				"بو زريده",
				"بردين",
				"البساتين",
				"بسرين",
				"بسوس",
				"بطلون",
				"بتاتر",
				"شاملخ",
				"شانيه",
				"شارون",
				"شرتون",
				"شملان",
				"شقيف بطلون",
				"ضهر الوحش",
				"دقون",
				"دير قوبل",
				"دفون",
				"دوير الرمان",
				"بلاط  سلفايا",
				"الفتيحات",
				"الوطا",
				"النجاصة",
				"الشويفات",
				"فساقين",
				"الغابون",
				"غادير",
				"حبرمون",
				"حارة شبيب",
				"حارة المير",
				"حارة سالم",
				"حي العرب",
				"حي السلم",
				"حي السنديانة",
				"حمص وحمى",
				"حومال",
				"اغميد",
				"جبل العريض",
				"جسر القاضي",
				"الكحاله",
				"كيفون",
				"كفرعميه",
				"كفرمتى",
				"خلدة",
				"كليلة",
				"معروفية",
				"معصريتي",
				"مجدليا",
				"منصورية بحمدون",
				"المنطرة",
				"مرج شرتون",
				"مزرعة البويت",
				"مزرعة النهر",
				"مشاقتي",
				"مشرفه",
				"مجدل بعنا",
				"المونسه عاليه",
				"مريجات عاليه",
				"الشويفات الامراء",
				"قبر شمون",
				"قماطية",
				"قبة الشويفات",
				"رام بشامون",
				"رملية",
				"رشميا",
				"رجمة",
				"رمحالا",
				"رجوم",
				"رويسات صوفر",
				"رويسة النعمان",
				"سرحمول",
				"سبعل",
				"سيل",
				"سلفايا",
				"صوفر",
				"سوق الغرب",
				"تعزانية",
				"تويته عين داره",
				"واطية",
				"ينار",
			],
		},
		{
			districtEn: "Mount Lebanon - Chouf",
			districtAr: "جبل لبنان - الشوف",

			citiesEn: [
				"Aalmane Ech Chouf",
				"Aammatour",
				"Aammiq chouf",
				"Aanout",
				"Aaqline",
				"Aatrine",
				"Aazibett tahta",
				"Ain Aazime",
				"Ain Bal",
				"Ain El Assad",
				"Ain el Haour",
				"Ain Ouzain",
				"Ain Qeni",
				"Ain Zhalta",
				"Almane ed Daiaa",
				"Baadarane",
				"Baal en Naame",
				"Baaqline",
				"Baasir",
				"Bachqiye",
				"Baiqoun",
				"Baqaoun",
				"Baqse",
				"Barja",
				"Barouk",
				"Bater",
				"Batloun",
				"Bchatfine",
				"Bchella Ech Chouf",
				"Beit ed Dine",
				"Benoeti",
				"Bire",
				"Bkechtine",
				"Bkifa",
				"Boqaata",
				"Borjein",
				"Boudine",
				"Boutme",
				"Bqaiaa",
				"Brih",
				"Bsaba",
				"Bsennay",
				"Bzina",
				"Chhim",
				"Chmaarine",
				"Chmis chouf",
				"Choualiq Deir El Qamar",
				"Chourit",
				"Dabche",
				"Dahr ech Chqif",
				"Dahr el Aaqline",
				"Dahr el Mghara",
				"Dalhoun",
				"Damour",
				"Daraiya",
				"Dawha",
				"Deir Baba",
				"Deir Dourite",
				"Deir El MKhales",
				"Deir el Qamar",
				"Deir er Rahbat",
				"Deir es Saide",
				"Deir Qouche",
				"Delghani",
				"Dhour Ain Al Haour",
				"Dibbiye",
				"Dmit",
				"Douair Ed Dibbiye",
				"Douair El Hara",
				"Ech Charbine",
				"Ed Dalhamiye",
				"Ej Jreid",
				"El Aaqbe joun",
				"El Battal",
				"El Kherbe",
				"El Khraibe",
				"El Meghraiqa",
				"El Msayed",
				"El Qateaa",
				"Eskandarouna",
				"Et Taamir",
				"Faouarat Jaafar",
				"Fraidiss",
				"Ghabet Jaafar",
				"Ghandouriye",
				"Gharife",
				"Haffet el Hajal",
				"Halioune el Faouqa",
				"Halioune et Tahta",
				"Hamra Ed Damour",
				"Hardouch",
				"Haret Aalmane",
				"Haret Baasir",
				"Haret Beit Madi",
				"Haret el Ouasta",
				"Haret en Naame",
				"Haret Jandal",
				"Hasrout",
				"Hjaijiye",
				"Jadra",
				"Jahliye",
				"Jall Bou Haidar",
				"Jamailiye",
				"Jbaa",
				"Jdaide chouf",
				"Je'ayel",
				"Jiblaye",
				"Jiye",
				"Jlailiye",
				"Joun",
				"Kahlouniye chouf",
				"Ketermaya",
				"Kfar Faqoud",
				"Kfar Hai",
				"Kfar Hamal",
				"Kfar Him",
				"Kfar Nabrakh",
				"Kfar Niss",
				"Kfar Qatra",
				"Khalouat Jernaya",
				"Khiam Ed Damour",
				"Khirbet Dabach",
				"Khirbit Bisri",
				"Khraibe chouf",
				"Knisse chouf",
				"Lahbiye",
				"Maaniye",
				"Maaser Beit ed Dine",
				"Maasser ech Chouf",
				"Majdalouna",
				"Majdel el Meouch",
				"Maqsabe",
				"Mar Mikheyel Ed Damour",
				"Mar Taqla En Naame",
				"Marj Aali",
				"Marj Barja",
				"Marj Ketermaya",
				"Marjiat",
				"Marjiat Borjein",
				"Mazboud",
				"Mazmoura",
				"Mazraat ech Chouf",
				"Mazraat ed Dahr",
				"Mazraat ed Doueir",
				"Mazraat El Barghoutiye",
				"Mazraat er Rzaniye",
				"Mazraat ez Zaitounniyeh",
				"Mazraat Khafiche",
				"Mechref",
				"Mermata",
				"Mghaire",
				"Mghairiye Chouf",
				"Mouhtaqara",
				"Moukhtara",
				"Mristi",
				"Mtaile",
				"Mtairiyat",
				"Mtoulle",
				"Naame",
				"Nabaa es Safa",
				"Nabi Younos",
				"Niha",
				"Ouadi Abou Youssef",
				"Ouadi Bnahle",
				"Ouadi Deir Dourit",
				"Ouadi ed Deir",
				"Ouadi es Sitt",
				"Ouadi Ez Zeyni",
				"Ouarhaniye",
				"Qalaat el Hosn",
				"Qalaat En Nimiri",
				"Qassoube",
				"Qraiaa",
				"Quardaniye",
				"Ras Aalous",
				"Rmaile",
				"Saadiyat",
				"Sabouniye",
				"Sahl Ej Jiye",
				"Samqaniye",
				"Saraouniye",
				"Sibline",
				"Sirjbal",
				"Souane Bsaba",
				"Traile",
				"Zaarour",
				"Zaarouriye",
			],
			citiesAr: [
				"علمان الشوف",
				"عمّاطور",
				"عميق الشوف",
				"عانوت",
				"عقلين",
				"عترين",
				"عزبيات التحتا",
				"عين عزيمة",
				"عينبال",
				"عين الاسد",
				"عين الحور",
				"عين وزين",
				"عين قني",
				"عين زحلتا",
				"علمان الضيعة",
				"بعدران",
				"بعل الناعمه",
				"بعقلين",
				"بعاصير",
				"باشقية",
				"بيقون",
				"بقعون",
				"بقسه",
				"برجا",
				"الباروك",
				"باتر",
				"بتلون",
				"بشتفين",
				"بشله الشوف",
				"بيت الدين",
				"بنواتي",
				"بيرة",
				"بكشتين",
				"بكيفا",
				"بقعاتا",
				"البرجين",
				"بودين",
				"بطمة",
				"بقيعة",
				"بريح",
				"بسابا",
				"بصّني",
				"بزينا",
				"شحيم",
				"شمعرين",
				"شميس",
				"شواليق دير القمر",
				"شوريت",
				"دبشه",
				"ضهر الشقيف",
				"ضهر عقلين",
				"ضهر المغارة",
				"دلهون",
				"الدامور",
				"داريا الشوف",
				"الدوحة",
				"دير بابا",
				"دير دوريت",
				"دير المخلص الشوف",
				"دير القمر",
				"دير الراهبات",
				"دير السيدة",
				"دير كوشه",
				"دلغاني",
				"ضهور عين الحور",
				"دبية",
				"دميت",
				"دوير الدبية",
				"دوير الحارة",
				"شربين",
				"دلهميه الدبيه",
				"جريد",
				"عقبة جون",
				"بطال",
				"الخربة الشوف",
				"خريبة بيرة الشوف",
				"مغريقا",
				"المصايد",
				"قتيعا",
				"إسكندرونة",
				"تعمير",
				"فوارة جعفر",
				"فريديس الشوف",
				"غابة جعفر",
				"غندورية",
				"غريفة",
				"حافة الحجل",
				"حليونة الفوقا",
				"حليونة التحتا",
				"حمرا الدامور",
				"حردوش",
				"حارة علمان",
				"حارة بعاصير",
				"حارة بيت ماضي",
				"حارة الواسطة",
				"حارة الناعمه",
				"حارة جندل",
				"حصروت",
				"حجاجية",
				"جدرا",
				"جاهلية",
				"جل بو حيدر",
				"جميلية",
				"جباع",
				"جديدة الشوف",
				"جعايل",
				"جبلايا",
				"جية",
				"جليلية",
				"جون",
				"كحلونية الشوف",
				"كترمايا",
				"كفرفاقود",
				"كفر حي",
				"كفر حمل",
				"كفرحيم",
				"كفرنبرخ",
				"كفرنيس",
				"كفرقطرة",
				"خلوات جرنايا",
				"خيام الدامور",
				"خربة دبش",
				"خربة بسري",
				"خريبة الشوف",
				"كنيسة الشوف",
				"لهبية",
				"معنيه",
				"معاصر بيت الدين",
				"معاصر الشوف",
				"مجدلونا",
				"مجدل المعوش",
				"مقصبة",
				"مار مخايل الدامور",
				"مار تقلا الناعمه",
				"مرج علي",
				"مرج برجا",
				"مرج كترمايا",
				"مرجيات",
				"برجين",
				"مزبود",
				"مزمورة",
				"مزرعة",
				"مزرعة الضهر",
				"مزرعة الدوير",
				"مزرعة البرغوتية",
				"مزرعة الرزَانية",
				"مزرعة الزيتونه",
				"مزرعة الخفيش",
				"مشرف",
				"مرماتا",
				"مغيره",
				"مغيرية  الشوف",
				"محتقره",
				"مختارة",
				"مرستى",
				"مطيلة",
				"مطيرية",
				"مطله",
				"ناعمه",
				"نبع الصفا",
				"نبي يونس",
				"نيحا",
				"وادي ابو يوسف",
				"وادي بنحليه",
				"وادي دير دوريت",
				"وادي الدير",
				"وادي الست",
				"وادي الزينة",
				"ورهانية",
				"قلعة الحصن",
				"قلعة النمري",
				"قصوبة",
				"قريعة",
				"وردانيه",
				"راس علوس",
				"رميلة",
				"السعديات",
				"صابونية",
				"سهل الجية",
				"سمقانية",
				"سرعونية",
				"سبلين",
				"سرجبال",
				"صوانة بسابا",
				"تريله",
				"زعرور",
				"زعرورية",
			],
		},
		{
			districtEn: "Mount Lebanon - Keserwan",
			districtAr: "جبل لبنان - كسروان",

			citiesEn: [
				"Aabri",
				"Aachqout",
				"Aafs kesrwane",
				"Aajaltoun",
				"Aarabe Ghosta",
				"Aaramoun Kesrwane",
				"Aayoun es Simane",
				"Aazrane",
				"Adonis Kesserwan",
				"Aghbe",
				"Ain Abaal",
				"Ain Ed Delbe",
				"Ain Ej Jorn",
				"Ain Er Rihane",
				"Ain Et Tannour",
				"Ain Jouaiya",
				"Aintoura",
				"Ayn Es Safra",
				"Bahhara",
				"Balloune",
				"Batha",
				"Bayader Fatqa",
				"Beit Eid",
				"Beit El Kreidi",
				"Beit Khachbou",
				"Beqaatet Aachqout",
				"Biqaatet Kannane",
				"Bizhel",
				"Bkirke",
				"Blat Mazraat Kfar Dibiane",
				"Bouar",
				"Bqaatouta",
				"Bqaq Ed Dine",
				"Broummana Kfar Dibian",
				"Bzoummar",
				"Chaab",
				"Chahtoul",
				"Chehhara",
				"Chnanaair",
				"Chouaya",
				"Chouene",
				"Christ Roi",
				"Daasse",
				"Dahr Badris",
				"Dahr el Qattine",
				"Daraaoun",
				"Darayia Kesrwane",
				"Dayr Saydet el Haqle",
				"Deir Baklouche",
				"Deir Hrach",
				"Deir Nisbey",
				"Deir Ram Bou Daqen",
				"Deir saydet Louaize",
				"Deir Ziraaya",
				"Delbta",
				"Deraali",
				"Dqarine",
				"Ech Chqif Bqaatouta",
				"Ed Dahr",
				"Ed Dahr Ghbale",
				"Ed Daoura Shaile",
				"Edma et Dafne",
				"Ej Jaayel",
				"El Aaqaybe Kesrouane",
				"El Aazra et el Aazr",
				"El Ghouabi",
				"El Hara Mairouba",
				"El Kharayeb",
				"El Kharayeb Dlebta",
				"El Maaden",
				"El Marji",
				"El Massiaf",
				"El Qacha",
				"El Qarqouf",
				"Es Salhiye Bezhel",
				"Es Shoum Kfar Debiane",
				"Es Slayekh",
				"Es Souhoum",
				"Esh Shahoute",
				"Et Tarouaa",
				"Ez Zaaytriye",
				"Faitroun",
				"Fanyoun",
				"Faqra",
				"Faraiya",
				"Fatqa",
				"Ftah Ech Chouha",
				"Ftahate",
				"Ghadir jounieh",
				"Ghadras",
				"Ghazir",
				"Ghbale",
				"Ghine",
				"Ghoshraiya",
				"Ghosta",
				"Hakl Er Raiyess",
				"Hamassiyat",
				"Haret El Mir Zouk Mkayel",
				"Haret Halane",
				"Haret Sakher",
				"Harharaya",
				"Hariqa",
				"Hariqa Chahtoul",
				"Harissa",
				"Hayata",
				"Hilane",
				"Hrajel",
				"Hsayn",
				"Jdaidet Ghazir",
				"Jitta",
				"Jouar El Baouechiq",
				"Jouar El Hachich chahtoul",
				"Jounieh",
				"Jounieh Kaslik",
				"Jouret Bedrane",
				"Jouret Ed Dardour",
				"Jouret Et Tormoss",
				"Jouret Mghad",
				"Kfar Hbab",
				"Kfar Jrif",
				"Kfardibiane",
				"Kfarshihham",
				"Kfaryassine",
				"Kfour",
				"Khalal",
				"Khdayra",
				"Ksayer",
				"Maamelteine",
				"Maarab",
				"Maaysra",
				"Mairouba",
				"Mar Nouhra",
				"Mashhat",
				"Mazzarat Er Ras",
				"Mchaa El Ftouh",
				"Mchaa Faraya",
				"Mchaa Kfar Dibian",
				"Mchati",
				"Mehqane el Mazloum",
				"Mghayer",
				"Mradiye",
				"Mrah El Mir",
				"Mreijet Kesserwan",
				"Nabaa el Mghara",
				"Nahr Ed Dahab",
				"Nahr El Hussein",
				"Nahr el Kalb",
				"Nammoura",
				"Nmoura",
				"Ouata Ej Jaouz",
				"Ouata el Laouz",
				"Ouata Nahr El Kelb",
				"Ouata Slam",
				"Qalaa Kfardibiane",
				"Qalaat Maarab",
				"Qarqara",
				"Qarqouf",
				"Qarsa",
				"Qattine",
				"Qlaiaat",
				"Qmayrze",
				"Qouwale",
				"Raashine",
				"Raifoun",
				"Ramiet Kfaryasin",
				"Rihane Kesrwane",
				"Safra kesrwane",
				"Sahel Aalma",
				"Saidet Bzoummar",
				"Sarba",
				"Shaile",
				"Sirje",
				"Snoubar",
				"Tabarja",
				"Talle",
				"Wata Tabriye",
				"Yahchouch",
				"Zaaitra",
				"Zayer",
				"Zeitoun",
				"Zleikat",
				"Zouk Mosbeh",
				"Zouq Mkayel",
			],
			citiesAr: [
				"عبري",
				"عشقوت",
				"عفص كسروان",
				"عجلتون",
				"عربة غوسطا",
				"عرمون كسروان",
				"عيون السيمان",
				"عزرانة",
				"أدونيس كسروان",
				"إغبة",
				"عين ابعل",
				"عين الدلبة",
				"عين الجرن",
				"عين الريحان",
				"عين التنور",
				"عين جويا",
				"عينطورة",
				"عين الصفرا",
				"بحارة",
				"بلونة",
				"بطحا",
				"بيادر فتقا",
				"بيت عيد",
				"بيت كريدي",
				"بيت خشبو",
				"بقعاتة عشقوت",
				"بقعاتة كنعان",
				"بزحل",
				"بكركي",
				"بلاط كفر ذبيان",
				"بوار",
				"بقعتوتا",
				"بقاق الدين",
				"برمانا كفر ذبيان",
				"بزمار",
				"شعب",
				"شحتول",
				"شحارة",
				"شننعير",
				"شويا يحشوش",
				"شوان",
				"يسوع الملك",
				"دعسه",
				"ضهر بدريس",
				"ضهر القطين",
				"درعون",
				"داريا كسروان",
				"دير سيدة الحقلة",
				"دير بقلوش",
				"دير حراش",
				"دير نسبيه",
				"دير رام بو دقن",
				"دير سيدة اللويزة",
				"دير زرعيا",
				"دلبتا",
				"درعليه",
				"دقارين",
				"شقيف بقعتوتا",
				"الضهر",
				"ضهر غبالة",
				"دورة سهيلة",
				"أدما والدفنه",
				"جعايل غبالة",
				"عقيبة",
				"عذره والعذر",
				"غوابي",
				"حارة ميروبا",
				"خرايب",
				"الخرايب دلبتا",
				"معادن",
				"مرج",
				"مصيف",
				"قشا",
				"القرقوف",
				"صالحية بزحل",
				"شوم كفر ذبيان",
				"السلايخ",
				"سوحوم الغينة",
				"الشاحوط",
				"التروع",
				"زعيترية",
				"فيطرون",
				"فنيوان",
				"فقرا",
				"فاريا",
				"فتقا",
				"فتاح الشوحا",
				"فتاحات جورة الترمس",
				"غادير جونيه",
				"غدراس",
				"غزير",
				"غبالة",
				"غينة",
				"غيشرايه",
				"غوسطا",
				"حقل الريس",
				"حماسيات",
				"حارة المير ذوق مكايل",
				"حارة حلان",
				"حارة صخر",
				"هرهريا",
				"حريقة",
				"حريق شحتول",
				"حريصا",
				"حياطة",
				"حلان",
				"حراجل",
				"حصين",
				"جديدة غزير",
				"جعيتا",
				"جوار البواشق",
				"جوار الحشيش شحتول",
				"جونيه",
				"جونيه كسليك",
				"جورة بدران",
				"جورة الدردور",
				"جورة الترمس",
				"جورة مهاد",
				"كفرحباب",
				"كفر جريف",
				"كفر دبيان",
				"كفر شيحام",
				"كفر ياسين",
				"الكفور",
				"خلال",
				"خضيره",
				"كساير",
				"معاملتين",
				"معراب",
				"المعيصرة",
				"ميروبا",
				"مار نهرا",
				"مشحات",
				"مزرعة الراس",
				"مشاع الفتوح",
				"مشاع فاريا",
				"مشاع كفر ذبيان",
				"مشاته",
				"محقان المظلوم",
				"المغاير",
				"مرادية",
				"مراح المير",
				"مريجة كسروان",
				"نبع المغارة",
				"نهر الدهب",
				"نهر الحصين",
				"نهر الكلب",
				"النموره",
				"نمورة",
				"وطى الجوز",
				"وطى اللوز",
				"وطى نهر الكلب",
				"وطى سلام",
				"قلعة كفر ذبيان",
				"قلعة معراب",
				"قرقرا",
				"القرقوف",
				"قرصة",
				"القطين",
				"قليعات كسروان",
				"قميزرة",
				"قواله",
				"رعشين",
				"ريفون",
				"رامية كفر ياسين",
				"ريحان كسروان",
				"صفرا كسروان",
				"ساحل علما",
				"دير سيدة بزمار",
				"صربا",
				"سهيلة",
				"سيرجه",
				"صنوبر يحشوش",
				"طبرجا",
				"تلة",
				"وطى طبرية",
				"يحشوش",
				"زعيتره",
				"زاير",
				"زيتون",
				"زليكات",
				"ذوق مصبح",
				"ذوق مكايل",
			],
		},
		{
			districtEn: "Mount Lebanon - Jbeil",
			districtAr: "جبل لبنان - جبيل",

			citiesEn: [
				"Aabeidat",
				"Aaboud",
				"Aafs jbeil",
				"Aainat",
				"Aalita",
				"Aamchit",
				"Aannaya",
				"Aaouaini",
				"Aaqoura",
				"Aarab el Lahib",
				"Aarasta",
				"Aayoun el Aalaq",
				"Adonis",
				"Afqa",
				"Ain Bqechqoch",
				"Ain ed Deir",
				"Ain Ed Delbe Jbeil",
				"Ain el Ghouaibe",
				"Ain el Qadah",
				"Ain es Salib",
				"Ain Ghalboun",
				"Ain Jrain",
				"Ain Kfaa",
				"Almat ech Chemaliye",
				"Almat Ej Jnoubiye",
				"Aydamoun",
				"Baachta",
				"Balhoss",
				"Barbara",
				"Barij",
				"Bchelli",
				"Bechtelida",
				"Behdaidat",
				"Beit El Boume",
				"Beit Hbaq",
				"Bejje",
				"Bekhaaz",
				"Bekouane",
				"Bentaael",
				"Berket Hejoula",
				"Beziyoun",
				"Bhassis",
				"Bir El Hait",
				"Bkourkaz",
				"Blat",
				"Bmehrine",
				"Boaatara",
				"Bqarta",
				"Broqta",
				"Chaabiyat el Fawqa",
				"Chaloumas",
				"Chamat",
				"Charbine Mazraat Es Siyad",
				"Chekhnaya",
				"Chikhane",
				"Chmout",
				"Chouata",
				"Daouret Edde Jbayl",
				"Deir el Qattara",
				"Deir Mar Maroun",
				"Deir Mar Sarkis",
				"Dmalsa",
				"Douar Bou chahine",
				"Doueir",
				"Ed Darje",
				"Edde",
				"Ehmej",
				"El Aafs",
				"El Aambra",
				"El Aarich",
				"El Barraniye",
				"El Bhayri",
				"El Biyade",
				"El Borj",
				"El Boustane",
				"El Houssoun",
				"El Hraifat",
				"El Marj Lassa",
				"El Mtolle",
				"El Owaynate",
				"El-Harf",
				"Ernaya",
				"Es Saqi",
				"Es Sare",
				"Fatre",
				"Ferhet",
				"Fghal",
				"Fidar",
				"Fidar el Faouqa",
				"Fidar Et Tahta",
				"Frat",
				"Ghabate",
				"Ghabline",
				"Ghalboun",
				"Gharfine",
				"Gharzouz",
				"Habboub",
				"Habil",
				"Halat",
				"Haqel",
				"Haqlet et Tine",
				"Hara Jbeil",
				"Harsha",
				"Hay El Aarbe",
				"Hay El Baalbakiye",
				"Hbalin",
				"Hedayne",
				"Heloue",
				"Hima Er Rehbane",
				"Hima Mar Maroun Aannaya",
				"Hjoula",
				"Hosn Aar",
				"Hosna",
				"Hosrayel",
				"Hourata",
				"Hrazmin",
				"Hsarat",
				"Jaj",
				"Janne",
				"Jbail",
				"Jdayel",
				"Jengel",
				"Jlaisse",
				"Jouret El Qattine",
				"Jrebta Jbeil",
				"Kafr",
				"Kelesh",
				"Kfar Chakha",
				"Kfar Chilli",
				"Kfar Hitta",
				"Kfar Kahli",
				"Kfar Kidda",
				"Kfar Mashoun",
				"Kfar Qaouass",
				"Kfar Sal",
				"Kfar Shabbouh",
				"Kfar Zbouna",
				"Kfarbaal",
				"Kfoun",
				"Khaab",
				"Khaabiya",
				"Kharbe",
				"Kour El Hooua",
				"Laqlouq",
				"Lassa",
				"Lehfed",
				"Maad",
				"Maaytiq",
				"Mahmarat Bejje",
				"Maifouq",
				"Majdel",
				"Malhoun",
				"Mar Meqna",
				"Marbaa",
				"Marj Mokhtara",
				"Mazraa Lassa",
				"Mazraat ej Jmaiyel",
				"Mazraat el Hajj Khalil",
				"Mazraat El Maadene",
				"Mazraat Es Siyad",
				"Mdamit",
				"Mechane",
				"Mechhellene",
				"MechMech Jbeil",
				"Meftah es Sellom",
				"Mestita",
				"Mghaira",
				"Mnaitra",
				"Monsef",
				"Mouftah el Mir",
				"Moukhada",
				"Mzarib",
				"Nabaa Tourzaiya",
				"Nahrh Ibrahim",
				"Naqour",
				"Ouata El Bane",
				"Ouata el bourj",
				"Ouata el Khirbe",
				"Qartaba",
				"Qartaboun",
				"Qass",
				"Qateaa",
				"Qattara",
				"Qehmez",
				"Qerqraiya",
				"Qeryaqous",
				"Ramiet el Hsoun",
				"Ramout",
				"Ras Osta",
				"Rihani",
				"Rouaiss",
				"Saqi Lassa",
				"Saqi Rechmaiya",
				"Saqiet ed Delb",
				"Saqiet el Khait",
				"Sariita",
				"Sbail",
				"Sebrine",
				"Serghol",
				"Sinnawr",
				"Sirine",
				"Slaiyeb Ghalboun",
				"Souane",
				"Souq el Firi",
				"Taht el Qalaa",
				"Talbita",
				"Tartij",
				"Tedmor",
				"Terouil",
				"Tourzaiya",
				"Wadi el Kalb",
				"Yanouh",
				"Zaayber",
				"Zebdine",
				"Zelhmaya",
				"Zmar",
			],
			citiesAr: [
				"عبيدات",
				"عبود",
				"عفص",
				"عينات",
				"عاليتا",
				"عمشيت",
				"عنَايا",
				"عويني",
				"عاقورة",
				"عرب اللهيب",
				"عرستا",
				"عيون العلاق",
				"ادونيس",
				"افقا",
				"عين بقشقش",
				"عين الدير",
				"عين الدلبة جبيل",
				"عين الغويبة",
				"عين القدح",
				"عين الصليب",
				"عين غلبون",
				"عين جرين",
				"عين كفاع",
				"علمات الشمالية",
				"علمات الجنوبية",
				"عيدامون",
				"بعشتا",
				"بلحص",
				"بربارة",
				"بريج",
				"بشلّلي",
				"بشتليدا",
				"بحديدات",
				"بيت البومة",
				"بيت حبّاق",
				"بجه",
				"بخعاز",
				"بكونا",
				"بنتاعل",
				"بركة حجولا",
				"بزيون",
				"بحسيس",
				"بير الهيت",
				"بكركز",
				"بلاط",
				"بمهرين",
				"بعتارا",
				"بقرتا",
				"برقتا",
				"شعبيات الفوقا",
				"شلوماس",
				"شامات",
				"شربين مزرعة السياد",
				"شخنايا",
				"شيخان",
				"شموت",
				"شواتا",
				"دورة إده جبيل",
				"دير القطارة",
				"دير مار مارون",
				"دير مار سركيس",
				"دملصا",
				"دوار بو شاهين",
				"الدوير",
				"درجه",
				"إده",
				"اهمج",
				"العفص",
				"العمبرا",
				"عريش",
				"برانية",
				"بحيري",
				"البياضة جبيل",
				"برج",
				"بستان يانوح",
				"حصون",
				"الحريفات",
				"مرج لاسا",
				"مطله جبيل",
				"عوينات",
				"حرف قرطبون",
				"ارنايا",
				"سقي",
				"سار",
				"فتري",
				"فرحت",
				"فغال",
				"الفيدار",
				"فدار الفوقا",
				"فدار التحتا",
				"فرات",
				"غابات",
				"غبالين",
				"غلبون",
				"غرفين",
				"غرزوز",
				"حبوب",
				"هابيل",
				"حالات",
				"حقل",
				"حقلة التينة",
				"حارة",
				"هرشا",
				"حي العربي",
				"حي البعلبكية",
				"حبالين",
				"هدينة",
				"حلوة",
				"حمى الرهبان",
				"حمى مار مارون عنَايا",
				"حجولا",
				"حصن العر",
				"حصنا",
				"حصرايل",
				"حوراتا",
				"حرازمين",
				"حصارات",
				"جاج",
				"جنة",
				"جبيل",
				"جدايل",
				"جونجل",
				"جليسه",
				"جورة القطين",
				"جربتا جبيل",
				"كفر",
				"كلش",
				"كفر شخي",
				"كفر شلي",
				"كفر حتى",
				"كفر كخلة",
				"كفر كده",
				"كفر مسحون",
				"كفر قواص",
				"كفر سالا",
				"كفر شبوح",
				"كفرزبونا",
				"كفر بعال",
				"كفون",
				"خعب",
				"خاعبية",
				"خاربة جبيل",
				"كور الهوا",
				"اللقلوق",
				"لاسا",
				"لحفد",
				"معاد",
				"معيتيق",
				"محمرة بجّه",
				"ميفوق",
				"المجدل",
				"ملحون",
				"مار مقانة",
				"مربعه",
				"مرج مختارة",
				"مزرعة لاسا",
				"مزرعة الجميل",
				"مزرعة الحاج خليل",
				"مزرعة المعادن",
				"مزرعة السياد",
				"مداميت",
				"مشان",
				"مشحلان",
				"مشمش جبيل",
				"مفتاح السلم",
				"مستيتا",
				"مغيره",
				"منيطرة",
				"المنصف",
				"مفتاح المير",
				"مخاضة",
				"المزاريب",
				"نبع طورزيا",
				"نهر ابراهيم",
				"نقور",
				"وطى البان",
				"وطى البرج",
				"وطى الخربة",
				"قرطبا",
				"قرطبون",
				"القص",
				"القاطعة",
				"قطارة",
				"قهمز",
				"قرقريا",
				"قرياقس",
				"رامية الحصون",
				"الراموط",
				"راس اسطا",
				"ريحانة",
				"رويس",
				"سقي لاسا",
				"سقي رشميا",
				"ساقية الدلب",
				"ساقية الخيط",
				"سرعيتا",
				"سبايل",
				"سربين",
				"سرغل",
				"سنور",
				"سيران",
				"صلايب غلبون",
				"صوانة",
				"سوق الفارة",
				"تحت القلعة",
				"تلبيتا",
				"ترتج",
				"تدمر",
				"ترويل",
				"طورزيا",
				"وادي الكلب",
				"يانوح",
				"زعيبر",
				"زبدين",
				"زلحمايا",
				"زمار",
			],
		},
		{
			districtEn: "Mount Lebanon - Matn",
			districtAr: "جبل لبنان - المتن",

			citiesEn: [
				"Aabdine",
				"Aafs",
				"Aairoun",
				"Aammariye",
				"Aaqbe Zalqa",
				"Aaraar",
				"Aatchane",
				"Abou Mizane",
				"Ain Aalaq",
				"Ain Aar",
				"Ain El Kharroube",
				"Ain El Qabou",
				"Ain el Qassis",
				"Ain el-Kach",
				"Ain Er Rihane el meten",
				"Ain Es Safsaf el meten",
				"Ain Es Sindiane",
				"Ain et Toufaha",
				"Ain Najm",
				"Ain Saade",
				"Ain Zaitoune",
				"Aintoura el meten",
				"Aiyoun",
				"Antelias",
				"Baabdat",
				"Baaqrif",
				"Balouaa",
				"Baouchriye",
				"Baskinta",
				"Bchellama",
				"Beit Chebab",
				"Beit El Koukko",
				"Beit Meri",
				"Belle Vue",
				"Beqaata En Nahr",
				"Bhannes",
				"Bhersaf",
				"Biaqout",
				"Bikfayia",
				"Bnabil",
				"Bolonia",
				"Borj Hammoud",
				"Bqennaya",
				"Broumana",
				"Bsalim",
				"Bsatine Ain Saade",
				"Bsifrine",
				"Bteghrine",
				"Chaouiye",
				"Chbouq",
				"Cherchar",
				"Cherin",
				"Chmis Antelias",
				"Chouaiya",
				"Choueir",
				"Dahr Broummana",
				"Dahr el Bacheq",
				"Dahr el Hossein",
				"Dahr Es Souane Meten",
				"Daoura",
				"Daychouniye",
				"Dbaiye",
				"Deir Chamra",
				"Deir el Qalaa",
				"Deir es Salib",
				"Deir Ma Yohanna El Khenchara",
				"Deir Mar Chaaya",
				"Deir Mar Jergos",
				"Deir Mar Simaane",
				"Deir Tamich",
				"Deir-er-Raai es Saleh",
				"Dekouane",
				"Delb",
				"Dhour Ech Choueir",
				"Dik El Mehdi",
				"Douar",
				"Ej Jouaniye",
				"El Borj El Khenchara",
				"El Braij Qornet Chahouane",
				"El Firdaous",
				"El Habach",
				"El Loueize",
				"El Machrah",
				"El Manazil",
				"El Qalaa",
				"El Qalaa Sin el fil",
				"En Naas",
				"En Nabaa",
				"Er Rabie",
				"Er Raouda",
				"Er Rouaisse",
				"Et Tabche",
				"Fanar",
				"Fanar ej Jdid",
				"Faouar",
				"Faouar el meten",
				"Fraike",
				"Ghabe",
				"Ghabet Bolonia",
				"Gharouch",
				"Hamlaya",
				"Haret el Bellane",
				"Haret el Cheikh",
				"Haret El Ghouarni",
				"Hbous",
				"Horch Tabet",
				"Jall Ed Dib",
				"Jdaide el Meten",
				"Jisr El Bacha",
				"Jouar",
				"Jouret El Ballout",
				"Kafra El Meten",
				"Kfar Aaqab",
				"Kfartay",
				"Khalle",
				"Khenchara",
				"Khirbit el Aadass",
				"Ksayfiyeh",
				"Machraa",
				"Majdel Tarchich",
				"Majzoub",
				"Makhadet Nahr el Kalb",
				"Mamboukh",
				"Mansouriye",
				"Mar Aabda el Mshammar",
				"Mar Boutrous Karm El- Tine",
				"Mar Mkhayel Bnabil",
				"Mar Mousa Ed Daouar",
				"Mar Roukoz",
				"Marj Baskinta",
				"Marjaba",
				"Masqa",
				"Mayasse",
				"Mazraat Beit Ech Chaar",
				"Mazraat Deir Aaoukar",
				"Mazraat El Hdaira",
				"Mazraat Yachoua",
				"Mchaymcheh",
				"Mcheikha",
				"Mezher",
				"Mhaydse",
				"Mkalless",
				"Montiverdi",
				"Mountazah",
				"Mrah Ghanem",
				"Mrouj",
				"Mtaileb",
				"Mtein",
				"Mzakke",
				"Nabay",
				"Naqqach",
				"Ouadi Chahine",
				"Ouadi ed Delb",
				"Ouadi El Amine",
				"Ouadi El Karm",
				"Ouata El Mrouj",
				"Qaaqour",
				"Qanat Bakich",
				"Qennabet Broummana",
				"Qennabet Salima",
				"Qnaitra El Meten",
				"Qornet Chahouane",
				"Qornet El Hamra",
				"Qottara Aintouret",
				"Raboue",
				"Ramie",
				"Raqayeq",
				"Ras el Jdaide",
				"Roumie",
				"Sabtiye",
				"Sad el Baouchriye",
				"Sannine",
				"Saqeit El Misk",
				"Sfaile",
				"sfaileh Bikfaya",
				"Sijn ej Jdid",
				"Sinn el Fil",
				"Tall ez Zaatar",
				"Wata Amaret Chalhoub",
				"Zaaitriye",
				"Zabbougha",
				"Zaghrine El Meten",
				"Zahriye El Meten",
				"Zalqa",
				"Zaraaoun",
				"Zikrit",
				"Zouk el Kharab",
			],
			citiesAr: [
				"عبدين نقاش",
				"عفص",
				"عيرون",
				"عمّارية",
				"عقبة الزلقا",
				"عرعار",
				"عطشانة",
				"أبو ميزان",
				"عين علق",
				"عين عار",
				"عين الخروبة",
				"عين القبو",
				"عين القسيس",
				"عين القش",
				"عين الريحان المتن",
				"عين الصفصاف المتن",
				"عين السنديانة",
				"عين التفاحة",
				"عين نجم",
				"عين سعادة",
				"عين الزيتونة",
				"عينطورة المتن",
				"عيون المتن",
				"انطلياس",
				"بعبدات",
				"بعقريف",
				"بالوع",
				"بوشرية",
				"بسكنتا",
				"بشلامة",
				"بيت شباب",
				"بيت الككو",
				"بيت مري",
				"بلّفو",
				"بقعاتا النهر",
				"بحنس",
				"بحرصاف",
				"بياقوت",
				"بكفيا",
				"بنابيل",
				"بولونيا",
				"برج حمّود",
				"بقنايا",
				"برمانا المتن",
				"بصاليم",
				"بساتين عين سعادة",
				"بسفرين",
				"بتغرين",
				"شاوية",
				"شبوق",
				"شرشار",
				"شرين",
				"شميس أنطلياس",
				"شويا",
				"شوير",
				"ضهر برمانا",
				"ضهر الباشق",
				"ضهر الحسين المتن",
				"ضهر الصوان المتن",
				"دورة",
				"ديشونية",
				"ضبية",
				"دير شمرا",
				"دير القلعة",
				"دير الصليب",
				"ديرمار يوحنا الخنشارة",
				"دير مار شعيا",
				"دير مار جرجس",
				"دير مار سمعان",
				"دير طاميش",
				"دير الراعي الصالح",
				"دكوانة",
				"دلب",
				"ضهور الشوير",
				"ديك المحدي",
				"دوار",
				"الجوانية",
				"برج الخنشارة",
				"بريج قرنة شهوان",
				"فردوس",
				"حباش",
				"لويزة نقاش",
				"مشرح",
				"منازل",
				"قلعة",
				"قلعة سن الفيل",
				"نعص",
				"النبعه",
				"رابيه",
				"روضة",
				"رويسة برمانا",
				"طبشة",
				"الفنار",
				"فنار الجديدة",
				"فوار",
				"فوار المتن",
				"فريكه",
				"غابة المسقى",
				"غابة بولونيا",
				"غاروش",
				"حملايا",
				"حارة البلان",
				"حارة الشيخ",
				"حارة الغوارني",
				"حبوس",
				"حرش تابت",
				"جل الديب",
				"جديدة المتن",
				"جسر الباشا",
				"جوار المتن",
				"جورة البلوط",
				"كفرا المتن",
				"كفرعقاب",
				"كفرتيه",
				"خلة المتين",
				"خنشارة",
				"خربة العدس",
				"قصيفية",
				"مشرع",
				"مجدل ترشيش",
				"مجذوب",
				"مخاضة نهر الكلب",
				"الممبوخ",
				"منصورية",
				"دير مار عبدا المشمر",
				"مار بطرس كرم التين",
				"مار مخايل بنابيل",
				"مار موسى الدوار",
				"مار روكز",
				"مرج بسكنتا",
				"مرجبا",
				"المسقى",
				"مياسة",
				"مزرعة بيت الشعّار",
				"مزرعة دير عوكر",
				"مزرعة الحضيرة",
				"مزرعة يشوع",
				"مشيمشة",
				"مشيخا",
				"مزهر",
				"محيدثة المتن",
				"مكلس",
				"منتفردي",
				"منتزه",
				"مراح غانم",
				"المروج",
				"مطيلب",
				"المتين",
				"مزكة",
				"نابيه",
				"نقاش",
				"وادي شاهين",
				"وادي الدلب",
				"وادي الامين",
				"وادي الكرم المتن",
				"وطى المروج",
				"القعقور",
				"قناة باكيش",
				"قنابة برمانا",
				"قنابة صليما",
				"قنيطرة المتن",
				"قرنة شهوان",
				"قرنة الحمرا",
				"قطارة عينطورة المتن",
				"ربوة",
				"رامية",
				"رقايق",
				"راس الجديدة",
				"روميه المتن",
				"سبتيه",
				"سد البوشرية",
				"صنين",
				"ساقية المسك",
				"سفيلة",
				"سفيلة بكفيا",
				"سجن الجديد",
				"سن الفيل",
				"تل الزعتر",
				"الوطى عمارة شلهوب",
				"زعيتريه",
				"زبوغا",
				"زغرين المتن",
				"زاهرية المتن",
				"الزلقا",
				"زرعون",
				"زكريت",
				"ذوق الخراب",
			],
		},
		{
			districtEn: "North Lebanon - Tripoli",
			districtAr: "شمال لبنان - طرابلس",

			citiesEn: [
				"Abou Samra",
				"Bab Al Ramel",
				"Bahsas",
				"Dam Wal Farz",
				"Ed Debbagha",
				"El Maloula",
				"El Mina",
				"Hadid",
				"Hdadine",
				"Jessrine",
				"Mankoubin",
				"Mhatreh",
				"MINA 1",
				"MINA 2",
				"Mina Jardin",
				"Noury",
				"Qalamoun",
				"Qoubbe",
				"Rammanet",
				"Shok",
				"Souayqa",
				"Tabbaneh",
				"Tal",
				"Trablous Jardins",
				"Trablous Zeitoun",
				"Tripoli",
				"Zahrieh",
			],
			citiesAr: [
				"ابو سمرا",
				"باب الرمل",
				"البحصاص",
				"الضم و الفرز",
				"الدباغة",
				"الملولة",
				"المينا",
				"الحديد",
				"الحدادين",
				"جسرين",
				"منكوبين",
				"المهاترة",
				"مينا طرابلس 1",
				"مينا طرابلس 2",
				"بساتين المينا",
				"النوري",
				"القلمون",
				"القبة",
				"الرمانة",
				"شق",
				"السويقة",
				"التبانة",
				"التل",
				"بساتين طرابلس",
				"طرابلس الزيتون",
				"طرابلس",
				"الزاهرية",
			],
		},
		{
			districtEn: "North Lebanon - Koura",
			districtAr: "شمال لبنان - الكورة",

			citiesEn: [
				"Aaba",
				"Aafsdiq",
				"Ain Aakrine",
				"Al-Hraiche",
				"Amioun",
				"Bahbouch",
				"Barghoun",
				"Barsa",
				"Batroumine",
				"Bdeihoun",
				"Bdibba",
				"Bechmizzine",
				"Bednayel el koura",
				"Bkeftine",
				"Bnehrane",
				"Bsarma",
				"Btaaboura",
				"Btouratij",
				"Btourram",
				"Bziza",
				"Dahr AlAin",
				"Dar Baachtar",
				"Dar Chmizzine",
				"Dedde",
				"El Aaqbe",
				"El Bahsas",
				"El Bqaiaa",
				"En Nakhle",
				"Enfe",
				"Fiaa",
				"Haret El KHASSEH",
				"Ijdabrine",
				"Jdeideh Berkacha",
				"Kaftoun",
				"Kefraiya",
				"Kfar Aaqqa",
				"Kfar Hata",
				"Kfar Hazir",
				"Kfar Qahel",
				"Kfar Saroun",
				"Kousba",
				"Majdel el Koura",
				"Metrit",
				"Oueta Fares",
				"Qalhat",
				"Ras Maska",
				"Ras Masqa Ech Chmaliye",
				"Ras Masqa Ej Jnoubiye",
				"Rechdibbine",
				"Zakroun",
				"Zakzouk",
				"Zgharta el Mtaouleh",
			],
			citiesAr: [
				"عبا الكورة",
				"عفصديق",
				"عين عكرين",
				"حريشه",
				"اميون",
				"بحبوش",
				"برغون",
				"برصا",
				"بترومين",
				"بدبهون",
				"بدبا",
				"بشمزين",
				"بدنايل الكورة",
				"بكفتين",
				"بنهران",
				"بصرما",
				"بتعبورة",
				"بتوراتيج",
				"بطرام",
				"بزيزا",
				"ضهر العين",
				"دار بعشتار",
				"دار شمزين",
				"دده",
				"عقبة",
				"بحصاص",
				"البقيعة",
				"نخلة",
				"أنفه",
				"فيع",
				"حارة الخسة",
				"اجدعبرين",
				"جديدة برقاشا",
				"كفتون",
				"كفريا الكورة",
				"كفر عقا",
				"كفرحاتا",
				"كفرحزير",
				"كفرقاهل",
				"كفرصارون",
				"كوسبا",
				"مجدل الكورة",
				"متريت",
				"وطى فارس",
				"قلحات",
				"راس مسقا",
				"راس مسقا الشمالية",
				"راس مسقا الجنوبية",
				"رشدبين",
				"زكرون",
				"زكزوك",
				"زغرتا المتاولة",
			],
		},
		{
			districtEn: "North Lebanon - Zgharta",
			districtAr: "شمال لبنان - زغرتا",

			citiesEn: [
				"IAAL",
				"Aachach",
				"Aalma",
				"Aaqbet Sibaal",
				"Aarbet Qozhaiya",
				"Aardat",
				"Aarjess",
				"Ain Tourine",
				"Aitou",
				"Al Aaqbe",
				"Arde",
				"Aslout",
				"Asnoun",
				"Baslouqit",
				"Bayader Rachaaine",
				"Bchama",
				"Bchannine",
				"Beit Aabeid",
				"Beit Aaoukar",
				"Beit Barakat",
				"Beit el Hraqsa",
				"Beit Knaty",
				"Bnechaai",
				"Bouhairet Toula",
				"Bousit",
				"Bsebaal",
				"Danha",
				"Darayia",
				"Ehden",
				"Ejbeaa",
				"El Hariq",
				"El Houakir",
				"El Khaldiye",
				"El Qadriye",
				"Er Rmaile",
				"Et Talle",
				"Fouwar zgharta",
				"Fradis",
				"Haouqa Et En Naher",
				"Haret al Fouwar",
				"Haret Ej Jdide Zgharta",
				"Haret el Baklik",
				"Harfe Arde",
				"Hariq Zgharta",
				"Harsoun Ej Jdide",
				"Hilane zgharta",
				"Hmais zgharta",
				"Hraykess",
				"Jdeide zgharta",
				"Kaabouch",
				"Kafar Zeina",
				"Kafraiya zgharta",
				"Karbribe",
				"Karm Sadde",
				"Kfar Chakhna",
				"Kfar Dlaqous",
				"Kfar Fou",
				"Kfar Haoura",
				"Kfar Hata",
				"Kfar Sghab",
				"Kfar Sghab",
				"Kfar Yachit",
				"Majdalaya zgharta",
				"Mar Semaane",
				"Mazraat Ejbeh",
				"Mazraat Et Toufah",
				"Mazraat Hraqs",
				"Mazraat Jnaid",
				"Mazret al Nahr",
				"Miryata",
				"Miziara",
				"Qarah Bach",
				"Qareit Sakhra",
				"Rachaaine",
				"Raskifa",
				"Sahl Danha",
				"Sakhra",
				"Sanaallah",
				"Sebaal",
				"Seraal",
				"Toula zgharta",
				"Zgharta",
			],
			citiesAr: [
				"إيعال",
				"عشاش",
				"علما",
				"عقبة سبعل",
				"عربة قزحيا",
				"عردات",
				"عرجس",
				"عينطورين",
				"أيطو",
				"عقبة علما",
				"أرده",
				"اسلوت",
				"اصنون",
				"بسلوقيت",
				"بيادر رشعين",
				"بشاما",
				"بشنين",
				"بيت عبيد",
				"بيت عوكر",
				"بيت بركات",
				"بيت الحرقصى",
				"بيت قناطي",
				"بنشعي",
				"بحيرة تولا",
				"بوسيط",
				"بسبعل",
				"دنها",
				"داريا",
				"اهدن",
				"اجبع",
				"حريق",
				"حواكير",
				"خالدية",
				"قادريه",
				"رميله أرده",
				"تلة زغرتا",
				"فوار زغرتا",
				"الفراديس",
				"حوقا النهر",
				"حارة الفوار",
				"حارة الجديدة زغرتا",
				"حارة البكليك",
				"حرف أرده",
				"حريق زغرتا",
				"حصرون الجديدة",
				"حيلان زغرتا",
				"حميص",
				"حريقص",
				"الجديدة زغرتا",
				"كبوش",
				"كفر زينا",
				"كفريا زغرتا",
				"كربريب",
				"كرم سده",
				"كفر شخنا",
				"كفردلاقوس",
				"كفر فو",
				"كفر حورا",
				"كفر حاتا",
				"كفرصغاب",
				"كفر ياشيت",
				"مجدليا زغرتا",
				"مار سمعان",
				"مزرعة إجبع",
				"مزرعة التفاح",
				"مزرعة حريقص",
				"مزرعة جنيد",
				"مزرعة النهر",
				"مرياطا",
				"مزيارة",
				"قره باش",
				"قرعية صخرا",
				"رشعين",
				"راس كيفا",
				"سهل دنها",
				"صخرة",
				"صنع الله",
				"سبعل زغرتا",
				"سرعيل",
				"تولا زغرتا",
				"زغرتا",
			],
		},
		{
			districtEn: "North Lebanon - Bcharri",
			districtAr: "شمال لبنان - بشري",

			citiesEn: [
				"Aabdine Bcharre",
				"Ariz",
				"Bane",
				"Barhalioun",
				"Bazaoun",
				"Bcharre",
				"Beit Menzer",
				"Billa",
				"Blaouza",
				"Bqaa Kafra",
				"Bqerqacha",
				"Braissat",
				"Chira",
				"Dimane",
				"Hadchit",
				"Hadet Ej jebbe",
				"Hasroun",
				"Kfar Saroun dimane",
				"Mazraat Assaf",
				"Mazraat Beni Saab",
				"Mchaa ej Joubbeh",
				"Moghr El Ahoual",
				"Qnaiouer",
				"Qnat",
				"Tourza",
				"Wadi Qannoubine",
			],
			citiesAr: [
				"عبدين بشري",
				"أرز",
				"بان",
				"برحليون",
				"بزعون",
				"بشري",
				"بيت منذر",
				"بلا",
				"بلوزا",
				"بقاع كفرا",
				"بقرقاشا",
				"بريسات",
				"شيرا",
				"ديمان",
				"حدشيت",
				"حدث الجبه",
				"حصرون",
				"كفر صارون الديمان",
				"مزرعة عساف",
				"مزرعة بني صعب",
				"مشاع الجبه",
				"مغر الاحول",
				"قنيور",
				"قناة",
				"طورزا",
				"وادي قنوبين",
			],
		},
		{
			districtEn: "North Lebanon - Batroun",
			districtAr: "شمال لبنان - البنرون",

			citiesEn: [
				"Aabdelle",
				"Aabrine",
				"Aalali",
				"Aaoura",
				"Aartez",
				"Ain el Batie",
				"Ain el Blat",
				"Ain er Raha",
				"Assia",
				"Balaa",
				"Barzakine",
				"Basbina",
				"Batroun",
				"Bcheale",
				"Bechtoudar-Aoura",
				"Beit Chlala",
				"Beit Kassab",
				"Bijdarfel",
				"Borj",
				"Boustane El Aassi",
				"Bqaiaa et Dahr Abi Yaghi",
				"Bqosmaiya",
				"Chabtine",
				"Chatine",
				"Chawi",
				"Chekka",
				"Chnata",
				"Daael",
				"Dahr Abi Yaghi",
				"Dahr el Ghbare",
				"Dahr El Qotlob",
				"Dahr Mar Risha",
				"Dawrat",
				"Dayr Shouwah",
				"Deir Billa",
				"Deir Kfifane",
				"Deir Mar Youhanna Douma",
				"Deir Mar Youssef Jrabta",
				"Derya",
				"Douma",
				"Douq",
				"Edde el Batroun",
				"El Aazeqa",
				"El Hamra JRANE",
				"El Harf",
				"El Heri",
				"El Khraize",
				"El Midane Kfifane",
				"El Qabaah",
				"En Nahriye",
				"Fadaous",
				"Fehta",
				"Ftahat",
				"Ghouma",
				"Hadtoun",
				"Hai el Birke",
				"Halta",
				"Hamat",
				"Hannouch",
				"Harbouna",
				"Hardine",
				"Harissa el batroun",
				"Hazrita",
				"Hourata el batroun",
				"Hrayek",
				"Ijdabra",
				"Jibla",
				"Joundi",
				"Jrane",
				"Jrebta",
				"Kandoula",
				"Kfar Aabida",
				"Kfar Chlaimane",
				"Kfar Hatna",
				"Kfar Hay",
				"Kfar Helda",
				"Kfarhollos",
				"Kfifane",
				"Kfour El Aarbi",
				"Koubba",
				"Kour",
				"Madfoun",
				"Mahmerch",
				"Mar Mama",
				"Mar Youhanna Maroun",
				"Mar Youssef",
				"Masrah",
				"Mazraat Biyade",
				"Meghrak",
				"Mrah Chdid",
				"Mrah El Haj",
				"Mrah Ez Zaiat",
				"Myle",
				"Nabaa ej Jdid",
				"Nahle batroun",
				"Najmet es Sobh",
				"Niha El Batroun",
				"Ouadi ej Jord",
				"Ouadi Tanourine Et Tahta",
				"Ouata Haub",
				"Qarnaoun",
				"Qornet el Marj",
				"Quajh El - Hajar",
				"Racha",
				"Rachana",
				"Rachkida",
				"Rachkidde",
				"Ram el batroun",
				"Ramate",
				"Ras Bnaiya",
				"Ras Ed Daouali",
				"Ras Nahhach",
				"Selaata",
				"Sghar",
				"Smar Jbail",
				"Sourat",
				"Ssel'aal",
				"Tannourine el Faouqa",
				"Tanourine Et Tahta",
				"Thoum",
				"Toula",
				"Yarita",
				"Zane",
			],
			citiesAr: [
				"عبدللي",
				"عبرين",
				"علالي",
				"عورا البترون",
				"عرطز",
				"عين البطيه",
				"عين البلاط",
				"عين الراحا",
				"اسيا",
				"بلعة",
				"برزقين",
				"بسبينا",
				"بترون",
				"بشعلة",
				"بشتودار",
				"بيت شلالا",
				"بيت كسّاب",
				"بجدرفل",
				"البرج كفر عبيدا",
				"بساتين العصي",
				"بقيعة البترون",
				"بقسميا",
				"شبطين",
				"شاتين",
				"شاوي",
				"شكَا",
				"شناتا",
				"داعل",
				"ضهر ابي ياغي",
				"ضهر الغبار",
				"ضهر القطلب",
				"ضهر مار ريشا",
				"دورة كفر عبيدا",
				"دير شواح",
				"ديربلا",
				"دير كفيفان",
				"دير مار يوحنا دوما",
				"دير مار يوسف جربتا",
				"دريا",
				"دوما",
				"دوق",
				"إده البترون",
				"عزيقه",
				"حمرا جران",
				"حرف",
				"هري",
				"خريزه",
				"ميدان كفيفان",
				"قبع كفيفان",
				"نهريه",
				"فدعوس",
				"فحتا",
				"فتاحات",
				"غوما",
				"حدتون",
				"حي البركة",
				"حلتا",
				"حامات",
				"حنٌوش",
				"حربونا",
				"حردين",
				"حريصا البترون",
				"حزريتا",
				"حوراتا البترون",
				"حرايق",
				"اجدبرا",
				"جبلا",
				"جندي",
				"جران",
				"جربتا",
				"قندولا",
				"كفر عبيدا",
				"كفر شليمان",
				"كفرحتنا",
				"كفرحي",
				"كفر حلدا",
				"كفر خلص",
				"كفيفان",
				"كفور العربي",
				"كوبا",
				"كور",
				"مدفون",
				"محمرش",
				"مار ماما",
				"مار يوحنا مارون",
				"مار يوسف",
				"مسرح",
				"مزرعة بياض",
				"مغراق",
				"مراح شديد",
				"مراح الحاج",
				"مراح الزيات",
				"ميل",
				"نبع الجديد",
				"نحلا  البترون",
				"نجمة الصبح",
				"نيحا البترون",
				"وادي الجرد",
				"وادي تنورين التحتا",
				"وطى حوب",
				"قرنعون",
				"قرنة المرج",
				"وجه الحجر",
				"راشا",
				"راشانا",
				"راشكيدا",
				"راشكِدّه",
				"الرام البترون",
				"رمات",
				"راس بنيه",
				"راس الدوالي",
				"راس نحاش",
				"سلعاتا",
				"صغار",
				"سمار جبيل",
				"صورات",
				"سلع",
				"تنورين الفوقا",
				"تنورين التحتا",
				"تحوم",
				"تولا",
				"ياريتا",
				"زان",
			],
		},
		{
			districtEn: "North Lebanon - Minieh-Danniyeh",
			districtAr: "شمال لبنان - المنية الضنية",

			citiesEn: [
				"Aadoui",
				"Aassaimout",
				"Aassoun",
				"Abou Hamad",
				"Afqa El Minieh",
				"Ain es Safsaf",
				"Ain Et Tine",
				"Amar",
				"Azqey",
				"Baazqoun",
				"Bahsa",
				"Bakhaoun",
				"Bchennata",
				"Bechhara",
				"Bechtayel",
				"Behouaita",
				"Beit Bakkour",
				"Beit Daoud Izal",
				"Beit El Faqs",
				"Beit Haouik",
				"Beit Hasna",
				"Beit jida",
				"Beit Kanj",
				"Beit Moumne",
				"Beit Radouane",
				"Beit Zoud",
				"Bhannine El Minieh",
				"Borj El Yahoudiye",
				"Bqaa Safrin",
				"Bqarsouna",
				"Btahline",
				"Btellaiye",
				"Btermaz",
				"Chmis",
				"Dairaiye",
				"Debaal El Minieh",
				"Deir Amar",
				"Deir Nbouh",
				"Ech Chalout",
				"El Beddaoui",
				"El Hazmiye",
				"El Kharnoub",
				"El Medine ej jdide",
				"El Minie",
				"En Nabi Kzaiber",
				"En Nabi Youchaa",
				"Er Rihaniye El Minieh",
				"Es Snoubar",
				"Haoura",
				"Haql El Aazime",
				"Haqlit",
				"Harf es siyad",
				"Izal",
				"Jairoun",
				"Jarjour",
				"Kahf El - Malloul",
				"Karm El - Mohr",
				"Karm El Akhras",
				"Kfar Bebnine",
				"Kfar Chillane",
				"Kfar Habou",
				"Kharnoub",
				"Maassarati",
				"Markabta",
				"Mazraat Aartoussi",
				"MAZRAAT EL KREYM",
				"Mgharet ech Cheikh",
				"Moulid",
				"Mrah Es Sfire",
				"Mrah Es Sreij",
				"Mrebbine",
				"Nemrine",
				"Ouadi En Nahle",
				"Ouatiye",
				"Qarhaiya",
				"Qarn",
				"Qarsita",
				"Qattine El Minieh",
				"Qemmamine",
				"Qraine",
				"Raouda",
				"Sertouka",
				"Sfire",
				"Sir Ed Danniye",
				"Souaqi",
				"Tarane",
				"Terbol El Minieh",
				"Wadi en Njass",
				"Zghartighrine",
				"Zouq Bhannine",
			],
			citiesAr: [
				"عدوة",
				"عصيموت",
				"عاصون",
				"ابو حمد",
				"افقا المنيه",
				"عين الصفصاف",
				"عين التينه المنيه",
				"عيمر",
				"عزقي",
				"بعزقون",
				"البحصة",
				"بخعون",
				"بشناتا",
				"بشحارة",
				"بشتايل",
				"بحويتا",
				"بيت بكور",
				"بيت داوود عزال",
				"بيت الفقس",
				"بيت حاويك",
				"بيت حسنة",
				"بيت جدا",
				"بيت كنج",
				"بيت مومنة",
				"بيت رضوان",
				"بيت زود",
				"بحنين المنيه",
				"برج اليهودية",
				"بقاع صفرين",
				"بقرصونه",
				"بتحلين",
				"بتلايه",
				"بطرماز",
				"الشميس",
				"داريا المنيه",
				"دبعل المنيه",
				"دير عمار",
				"دير نبوح",
				"شالوط",
				"بداوي",
				"حازمية المنيه",
				"خرنوب المنيه",
				"مدينة الجديدة",
				"المنيه",
				"النبي كزيبر",
				"النبي يوشع",
				"ريحانيه  المنيه",
				"صنوبر",
				"حوارة",
				"حقل العزيمة",
				"حقلة",
				"حرف السياد",
				"إيزال",
				"جيرون",
				"جرجور",
				"كفَ الملول",
				"كرم المهر",
				"كرم الاخرس",
				"كفر ببنين",
				"كفر شلان",
				"كفر حبو",
				"خرنوب",
				"معصراتي",
				"مركبتا",
				"مزرعة عرطوسي",
				"مزرعة الكريم",
				"مغارة الشيخ",
				"موليد",
				"مراح السفيرة",
				"مراح السريج",
				"مربين",
				"نمرين",
				"وادي النحلة",
				"واطيه",
				"قرحيا",
				"القرن",
				"قرصيتا",
				"القطين المنيه",
				"قمامين",
				"قرين",
				"روضه المنيه",
				"سرتوكا",
				"سفيرة",
				"سير الضنية",
				"السواقي",
				"طاران",
				"تربل المنيه",
				"وادي النجاص",
				"زغرتغرين",
				"ذوق بحنين",
			],
		},
		{
			districtEn: "South Lebanon - Sidon",
			districtAr: "جنوب لبنان - صيدا",

			citiesEn: [
				"Aabra",
				"Aaddoussiye",
				"Aadloun",
				"Aanqoun",
				"Aaqbiye",
				"Aaqtanit",
				"Aarnaba",
				"Abou el Assouad",
				"Ain Ed Delb",
				"Ain el Hiloue",
				"Arkey",
				"Arzay",
				"Babliye",
				"Barti",
				"Bissariyeh",
				"Bnaafoul",
				"Bqosta",
				"Brak et Tall",
				"Bramiye",
				"Daoudiye",
				"Darb es Sim",
				"Deir Taqla",
				"Dekerman",
				"Dhour Darb es Sim",
				"El Achrafiye",
				"El Mahmoudiye",
				"Er Rouayess",
				"Ez Zahrani",
				"Ghassaniye",
				"Ghaziye",
				"Hababiye",
				"Hajje",
				"Haret Saida",
				"Hartai",
				"Hlaliye Saida",
				"Insariye",
				"Jazire",
				"Jdaide Arzai",
				"Jinjlaya",
				"Kafraiya",
				"Kaouthariyet es Siyad",
				"Kfar Badde",
				"Kfar Beit",
				"Kfar Chellal",
				"Kfar Hatta",
				"Kfar Melki Saida",
				"Khannoussiye",
				"Kharayeb Saida",
				"Khartoum",
				"Khaziz",
				"Khirbet Ain el Qanater",
				"Khirbet Bassal",
				"Khirbet ed Daoueir",
				"Loubiye",
				"Maamriye",
				"Maamriyet el Kharab",
				"Maghdouche",
				"Majdelyoun",
				"Maqsam El  JAOUHARI",
				"Matariyet ech Choumar",
				"Mazraat Aabboudiye",
				"Mazraat Aarab ej Jall",
				"Mazraat Ain el Qantara",
				"Mazraat Arab Soukkar",
				"Mazraat Arab Tobbaya",
				"Mazraat ej Joudaye",
				"Mazraat el Aite Niye",
				"Mazraat el Daoudiye",
				"Mazraat el Hsainiye",
				"Mazraat el Ouasta",
				"Mazraat el Yahoudiye",
				"Mazraat Iskandarouna",
				"Mazraat Jemjim",
				"Mazraat Khaizarane",
				"Mazraat Khoutaryet er Rezz",
				"Mazraat Matariyet Jbaa",
				"Mazraat Sekkaniye",
				"Mazraat Sinai",
				"Mazraat Zaita",
				"Merouaniye",
				"Mghairiye",
				"Mhaidle",
				"Miyeh ou Miyeh",
				"Mrah Kiouane",
				"Msaileh",
				"Najjaryie",
				"Oussamiyat",
				"Qaaqaaii es Snoubar",
				"Qennarit",
				"Qiyaa",
				"Qnaitra",
				"Qraiye Saida",
				"Saida",
				"Saida Ed Dekermane",
				"Saksakiye",
				"Salhiye",
				"Sarafand",
				"Sari",
				"Sfenti",
				"Sinai",
				"Snaiber",
				"Tanbourit",
				"Tebna",
				"Toufahta",
				"Wastani",
				"Zaghdraiya",
				"Zaita",
				"Zrariye",
			],
			citiesAr: [
				"عبرا",
				"عدّوسية",
				"عدلون",
				"عنقون",
				"العاقبية",
				"عقتنيت",
				"عرنابة",
				"ابو الاسود",
				"عين الدلب",
				"عين الحلوة",
				"اركي",
				"أرزي",
				"بابلية",
				"برتي",
				"بيسارية",
				"بنعفول",
				"بقسطا",
				"براك التل",
				"برامية",
				"الداودية",
				"درب السيم",
				"دير تقلا",
				"الدكرمان",
				"ضهور درب السيم",
				"أشرفية المية ومية",
				"محمودية",
				"روايس",
				"الزهراني",
				"غسانية",
				"غازية",
				"حبابية",
				"حجة",
				"حارة صيدا",
				"حارتية",
				"هلالية صيدا",
				"إنصارية",
				"جزيرة صيدا",
				"جديدة  أرزي",
				"جنجلاية",
				"كفريا",
				"كوثرية السياد",
				"كفر بدَه",
				"كفربيت",
				"كفر شلال",
				"كفرحتى",
				"كفرملكي صيدا",
				"خنوسية",
				"الخرائب صيدا",
				"خرطوم",
				"خزيز",
				"خربة عين القناطر",
				"خربة البصل",
				"خربة الدوير صيدا",
				"لوبية",
				"معمارية",
				"معمرية الخراب",
				"مغدوشة",
				"مجدليون",
				"مقسم الجوهري",
				"مطرية الشومر",
				"مزرعة العبودية",
				"مزرعة عرب الجل",
				"مزرعة عين القنطرة",
				"مزرعة عرب سكر",
				"مزرعة عرب  طبَايا",
				"مزرعة الجودية",
				"مزرعة العيتانية",
				"مزرعة الداودية",
				"مزرعة الحسينية",
				"مزرعة الواسطة",
				"مزرعة  اليهودية",
				"مزرعة إسكندرونة",
				"مزرعة جمجيم",
				"مزرعة خيزران",
				"مزرعة كوثرية الرز",
				"مزرعة مطيرية جباع",
				"مزرعة السكنية",
				"مزرعة سيناي",
				"مزرعة زيتا",
				"مروانية",
				"مغيرية",
				"المحيدلة",
				"مية ومية",
				"مراح كيوان",
				"المصيلح",
				"نجارية",
				"الاوساميات",
				"قعقعية الصنوبر",
				"قناريت",
				"قياعة",
				"القنيطرة",
				"قرية صيدا",
				"صيدا",
				"صيدا الدكرمان",
				"سكسكية",
				"صالحية",
				"صرفند",
				"ساري",
				"سفنتا",
				"سيناي",
				"مزرعة سنيبر",
				"طنبوريت",
				"تبنا",
				"تفاحتا",
				"الوسطاني",
				"زغدرايا",
				"زيتا",
				"زرارية",
			],
		},
		{
			districtEn: "South Lebanon - Tyre",
			districtAr: "جنوب لبنان - صور",

			citiesEn: [
				"Aabbassiye",
				"Aaitit",
				"Aalma ech Chaab",
				"Aamrane",
				"Aazziye",
				"Abou Chach",
				"Ain Abu Aabdalla",
				"Ain Baal",
				"Arzoun",
				"Bafliye",
				"Barich",
				"Batouliye",
				"Bazouriye",
				"Bedias",
				"Bestiyat",
				"Biyad Sour",
				"Borj ech Chmali",
				"Borj el Haoua",
				"Borj el Qibli",
				"Borj Rahhal",
				"Bourghliye",
				"Boustane Sour",
				"Btaichiye",
				"Chaaitiyeh",
				"Chabriha",
				"Chahour",
				"Chamaa",
				"Charnaiye",
				"Chehabiye",
				"Chihine",
				"Debaal",
				"Deir Aamess",
				"Deir Kifa",
				"Deir Qanoun",
				"Deir Qanoun en Nahr",
				"Derdghaiya",
				"Dhaira",
				"Ech Choumara",
				"Ed Dikiye",
				"El Bass",
				"El Biyada",
				"El Borj En-Naqoura",
				"El Kleile",
				"El Ouardani",
				"Er Rafid",
				"Hallousiyet el Faouqa",
				"Halloussiye",
				"Hammadiye",
				"Hamoul",
				"Hannaouiye",
				"Hanniye",
				"Haumeiri",
				"Iskandarouna Sour",
				"Jannata",
				"Jbal el Botm",
				"Jebbain",
				"Jijim",
				"Jouaiya",
				"Jour en Nakhl",
				"Kfarnay",
				"Knisse Sour",
				"Labboune",
				"Maachouq",
				"Maaliye",
				"Maarake",
				"Maaroub",
				"Machta El Aaziye",
				"Mahrouneh",
				"Majdel Zoun",
				"Malkeit es Sahel",
				"Mansouri",
				"Marnaba",
				"Marouahine",
				"Matmoura",
				"Mazraat Aaiye",
				"Mazraat Ain ez Zarqa",
				"Mazraat Biout es Siyad",
				"Mazraat Bsaile",
				"Mazraat Deir Hanna",
				"Mazraat Mechref",
				"Mheilib",
				"Mjadel",
				"Nabi Qassem",
				"Naffakhiye",
				"Naqoura",
				"Niha Sour",
				"Ouadi Jilou",
				"Oum Toute",
				"Qalaat Maroun",
				"Qana",
				"Qasmiye",
				"Rachidiye",
				"Ras el Ain",
				"Rechkananey",
				"Rmadiyeh",
				"Salaa",
				"Sammaaiye",
				"Siddiqine",
				"Sour",
				"Srifa",
				"Taibe Sour",
				"Tair Debba",
				"Tair Filsay",
				"Tair Harfa",
				"Tair Semhat",
				"Tair Zebna",
				"Touairi",
				"Toura",
				"Yarine",
				"Ynouh",
				"Zabqine",
				"Zahriye",
				"Zalloutiye",
			],
			citiesAr: [
				"عباسية",
				"عيتيت",
				"علما الشعب",
				"عمران",
				"عزِّيه",
				"أبو شاش",
				"عين أبو عبدالله",
				"عين بعل",
				"ارزون",
				"بافليه",
				"باريش",
				"باتوليه",
				"بازورية",
				"بدياس",
				"بستيات",
				"البياض صور",
				"برج الشمالي",
				"برج الهوا",
				"برج قبلي",
				"برج رحال",
				"برغلية",
				"بستان صور",
				"بطيشية",
				"شعيتية",
				"شبريحا",
				"شحور",
				"شمع",
				"شارنية",
				"شهابية",
				"شيحين",
				"دبعل",
				"ديرعامص",
				"دير كيفا",
				"دير قانون",
				"دير قانون النهر",
				"دردغايا",
				"ظهيرة",
				"الشومارا",
				"الديكية",
				"البصَ",
				"بياضة",
				"برج الناقورة",
				"قليلة",
				"ورداني",
				"الرافد",
				"حلوسية الفوقا",
				"حلوسية",
				"حمَادية",
				"حامول",
				"حناوي",
				"حنية",
				"حميري",
				"إسكندرونة",
				"جناتا",
				"جبال البطم",
				"جبين",
				"ججيم",
				"جويا",
				"جوار النخل",
				"كفرنية",
				"كنيسة صور",
				"لبونة",
				"معشوق",
				"معليَة",
				"معركة",
				"معروب",
				"مشتى العزِية",
				"محرونه",
				"مجدل زون",
				"مالكية الساحل",
				"المنصوري",
				"مرنبا",
				"مروحين",
				"المطمورة",
				"مزرعة عيا",
				"مزرعة عين الزرقا",
				"مزرعة بيوت السياد",
				"مزرعة بسيلة",
				"مزرعة دير حنا",
				"مزرعة المشرف",
				"محيليب",
				"المجادل",
				"نبي قاسم",
				"نفاخية",
				"الناقورة",
				"نيحا صور",
				"وادي جيلو",
				"ام التوت",
				"قلعة مارون",
				"قانا",
				"قاسمية",
				"الرشيدية",
				"راس العين",
				"رشكنانيه",
				"رمادية",
				"سلعا",
				"سماعية",
				"صديقين",
				"صور",
				"صريفا",
				"الطيبة صور",
				"طير دبّه",
				"طير فلسيه",
				"طير حرفا",
				"طير سمحات",
				"طير زبنا",
				"طويري",
				"طورا",
				"يارين",
				"يانوح صور",
				"زبقين",
				"زهيرية",
				"مزرعة الزلوطية",
			],
		},
		{
			districtEn: "South Lebanon - Jezzine",
			districtAr: "جنوب لبنان - جزين",

			citiesEn: [
				"Aadour",
				"Aaichiye",
				"Aaqmata",
				"Aaramta",
				"Aariye",
				"Aarqoub",
				"Aazour",
				"Ain el Mir el Estabel",
				"Ain et Taghra",
				"Ain Majdalain",
				"Anane",
				"Azibeh",
				"Baanoub",
				"Baba",
				"Baissour Jezzine",
				"Benouati",
				"Bhannine",
				"Bisri",
				"Biyad",
				"Bkassine",
				"Bouslaya",
				"Bteddine el Loqch",
				"Chamkha",
				"Chbeil",
				"Choualiq",
				"Dahr ed Deir",
				"Dahr er Ramle",
				"Darayia Jezzine",
				"Deir Chkedif",
				"Deir El Qattine",
				"Deir Machmouche",
				"Deir Moukhalles",
				"Dimechqiye",
				"El Harf Jezzine",
				"El Houraniye",
				"El Msous",
				"El Qabaa",
				"Ghbatiye",
				"Haidab",
				"Haitoule",
				"Haitoura",
				"Haret el Bayder",
				"Harf",
				"Hassaniye",
				"Homsiye",
				"Jabal Toura",
				"Jall Nachi",
				"Jarmaq",
				"Jdaidet el Ouadi",
				"Jensnaya",
				"Jernaya",
				"Jezzine",
				"Karkha",
				"Kfar Falous",
				"Kfar Houne",
				"Kfar Jarra",
				"Kfar Taala",
				"Khallet Khazen",
				"Khirkhaya",
				"Lebaa",
				"Louaiziye",
				"Maarous el Branieh",
				"Maarous el Jouanieh",
				"Machmouche",
				"Mahmoudiye Jezzine",
				"Maknouniye",
				"Mazraat  Aarqoub",
				"Mazraat  Jabal Toura",
				"Mazraat  Tamra",
				"Mazraat Aadour",
				"Mazraat Aaqmata",
				"Mazraat Aaraji",
				"Mazraat Al Souairi",
				"Mazraat el Btadiniye",
				"Mazraat el Khaoukh",
				"Mazraat el Mathane",
				"Mazraat er Rohbane",
				"Mazraat Louzyde",
				"Mharbiye",
				"Midane",
				"Mjaydel",
				"Mlikh",
				"Mrah Abdu Chedid",
				"Mrah El Hbas",
				"Mrah Mghaibe",
				"Mzairaa",
				"Nabaa",
				"Nabi Sejoud",
				"Ouadi Baanqoudine",
				"Ouadi el Leimoun",
				"Ouardiye",
				"Ouazaaiye",
				"Qaitoule",
				"Qotrani",
				"Qrouh",
				"Qtale Jezzine",
				"Raimat",
				"Rihane Jezzine",
				"Roum",
				"Roummane Jezzine",
				"Rous El Franj",
				"Sabah",
				"Salima",
				"Sejoud",
				"Sfarai",
				"Sidoun",
				"Sniye",
				"Sriri",
				"Taaid",
				"Tamra",
				"Wadi Jezzine",
				"Zaghrine Jezzine",
				"Zhalta",
			],
			citiesAr: [
				"عاضور",
				"عيشية",
				"عقماتا",
				"عرمتى",
				"عاريه",
				"العرقوب",
				"عازور",
				"عين المير إسطبل",
				"عين التغرى",
				"عين مجدلين",
				"أنان",
				"عزيبة",
				"بعانوب",
				"بيبه",
				"بيصور جزين",
				"بنواتي جزين",
				"بحنين",
				"بسري",
				"البياض",
				"بكاسين",
				"بوصلايا",
				"بتدين اللقش",
				"شامخة",
				"شبيل",
				"شواليق جزين",
				"ضهر الدير",
				"ضهر الرملة",
				"داريا جزين",
				"شقاديف",
				"دير قطِين",
				"دير مشموشه",
				"دير  المخلص",
				"دمشقية",
				"الحرف جزين",
				"حورانية",
				"مصوص",
				"قبع",
				"غبَاطية",
				"حيداب",
				"حيتوله",
				"حيطورة",
				"حارة البيادر",
				"الحرف",
				"حسانية",
				"حمصية",
				"جبل طوره",
				"جل ناشي",
				"الجرمق",
				"الجديدة وادي جزين",
				"جنسنايا",
				"جرنايا",
				"جزين",
				"كرخا",
				"كفرفالوس",
				"كفرحون",
				"كفرجرا",
				"كفرتعلا",
				"خلة خازن",
				"خرخيا",
				"لبعا",
				"لويزة جزين",
				"ماروس البرانية",
				"ماروس الجوانية",
				"مشموشة",
				"محمودية جزين",
				"مكنونية",
				"مزرعة العرقوب",
				"مزرعة جبل طوره",
				"مزرعة طمره",
				"مزرعة عاضور",
				"مزرعة عقماتا",
				"مزرعة عراجي",
				"مزرعة الصويري",
				"مزرعة البتدينية",
				"مزرعة الخوخ",
				"مزرعة المطحنة",
				"مزرعة الرهبان",
				"مزرعة لوزيد",
				"محاربية",
				"ميدان",
				"مجيدل",
				"مليخ",
				"مراح أبو شديد",
				"مراح الحباس",
				"مراح مغبيه",
				"مزيرعة",
				"نبعه",
				"نبي سجد",
				"وادي بعنقودين",
				"وادي الليمون",
				"وردية",
				"اوزاعية",
				"قيتولي",
				"قطراني",
				"قروح",
				"قتالة جزين",
				"ريمات",
				"ريحانة جزين",
				"روم",
				"رمانة",
				"راس الوادي الحوة",
				"صّباح",
				"صليما",
				"سجد",
				"صفاريه",
				"صيدون",
				"سنيَا",
				"سريرة",
				"تعيد",
				"طمره",
				"وادي جزين",
				"زغرين جزين",
				"زحلتا",
			],
		},
		{
			districtEn: "Bekaa - Zahle",
			districtAr: "البقاع - زحلة",

			citiesEn: [
				"Aali en Nahri",
				"Ablah",
				"Ain el Ghmiqa",
				"Ain Kfar Zabad",
				"Al Faour",
				"Anjar",
				"Bar Elias",
				"Bayyadat",
				"Berbara zahle",
				"Bouarej",
				"Chamssine",
				"Chebrqiyet Tabet",
				"Chtaura",
				"Dahr al Harf",
				"Dahr Blait",
				"Dahr es Souane",
				"Dalhamiye",
				"Deir el Ghazal",
				"Deir Zenoun",
				"Er Ramtaniye",
				"Es Sraij",
				"Fourzol",
				"Hakl Hammana",
				"Haouch ed Dibs",
				"Haouch el Mendara",
				"Haouch el Oumara Aradi",
				"Haouch el Sayade",
				"Haouch Moussa Anjar",
				"Haret el Fikani",
				"Hazerta",
				"Hechmech",
				"Houch El-Ghanam",
				"Houch ez Zaraane",
				"Houch Hala",
				"Jdita",
				"Jlala",
				"Karak Nouh",
				"Kfar Zabad",
				"Koussaya",
				"Ksara",
				"MADINAT AL SINA'IYAT",
				"Majdel Anjar",
				"Mar Elias Zahle",
				"Masnaa Zahle",
				"Massa",
				"Mazraat el Mehqane",
				"Mazraat Zahle",
				"Meksi",
				"Mreijat",
				"Naassate",
				"Nabi Aila",
				"Nasriyet Rizq",
				"Nasriyet Zahle",
				"Niha zahle",
				"Ouadi ed Deloum",
				"Ouadi el Aarayech",
				"Qaa er Rim",
				"Qabb Elias",
				"Qarqoud",
				"Qeisser",
				"Qommol",
				"Raait",
				"Ras el Ain Zahle",
				"Rassiyeh",
				"Rayak",
				"Saadnayel",
				"Sahret el Qach",
				"Taalabaya",
				"Taanayel",
				"Tall el Akhdar",
				"Tcheflik Eddeh Haouch",
				"Tcheflik Qiqano",
				"Tell Chiha",
				"Tell el Aamara",
				"Terbol",
				"Touaite",
				"Zahle",
				"Zahle  Mar Antonios",
				"Zahle  Mar Gerges",
				"Zahle  Saydet En Najat",
				"Zahle Aradi",
				"Zahle Maalaqa Aradi",
				"Zebdol",
			],
			citiesAr: [
				"علي النهري",
				"ابلح",
				"عين الغميقة",
				"عين كفر زبد",
				"الفاعور",
				"عنجر",
				"بر الياس",
				"البياضة",
				"بربارة زحلة",
				"بوارج",
				"شمسين",
				"شبرقية تابت",
				"شتورا",
				"ضهر الحرف",
				"ضهر البلايط",
				"ضهر الصوان",
				"دلهميه",
				"دير الغزال",
				"دير زنون",
				"الرمطانية",
				"سريج",
				"فرزل",
				"حقل حمانا",
				"حوش الدبس",
				"حوش مندره",
				"زحلة حوش الامراء أراضي",
				"حوش الصيادي",
				"حوش موسى عنجر",
				"حارة الفيكاني",
				"حزرتا",
				"حشمش",
				"حوش الغنم",
				"حوش الزراعنة",
				"حوش حالا",
				"جديتا",
				"جلالا",
				"كرك نوح",
				"كفر زبد",
				"قوسايا",
				"كسارة",
				"مدينة الصناعية",
				"مجدل عنجر",
				"مار الياس زحلة",
				"المصنع زحلة",
				"مسا",
				"مزرعة المحقان",
				"مزرعة زحلة",
				"مكسة",
				"مريجات",
				"نعصات",
				"نبي ايلا",
				"ناصرية رزق",
				"ناصرية  زحلة",
				"نيحا زحلة",
				"وادي الدلم",
				"وادي العرايش",
				"قاع الريم",
				"قب الياس",
				"قرقود",
				"قيصر",
				"قّمّل",
				"رعيت",
				"راس العين زحلة",
				"الراسية",
				"رياق",
				"سعدنايل",
				"صحرة القش",
				"تعلبايا",
				"تعنايل",
				"تل الاخضر",
				"تشفلك اده حوش",
				"تشفلك قيقانو",
				"تل شيحا",
				"تل العمارة",
				"تربل",
				"تويتي",
				"زحلة",
				"زحلة مار أنطونيوس",
				"زحلة مار جرجس",
				"زحلة  سيدة النجاة",
				"زحلة أراضي",
				"زحلة معلقة أراضي",
				"زبدل",
			],
		},
		{
			districtEn: "Bekaa - West Bekaa",
			districtAr: "البقاع الغربي",

			citiesEn: [
				"Aammiq",
				"Aana",
				"Ain et Tine West Bekaa",
				"Ain Zebde",
				"Aitanit",
				"Al-Wakf",
				"Baaloul",
				"Bab Maraa",
				"Chebreqiyet Aammiq",
				"Dakoue",
				"Deir Ain ej Jaouze",
				"Deir Tahnich",
				"El Jezire",
				"El Marj",
				"Ghazze",
				"Hammara",
				"Harime es Soughra",
				"Houch Aammiq",
				"Houch el Harime",
				"Houch es Saalouk",
				"Joub Jannine",
				"Kafraiya West Bekaa",
				"Kamed el Laouz",
				"Khiara",
				"Khiara el Aatiqa",
				"Khirbet Qanafar",
				"Lala",
				"Libbaya",
				"Loussia",
				"Machgara",
				"Mansoura",
				"Meidoun",
				"Nabaa el Khraizat",
				"Qaraoun",
				"Qillaya",
				"Raouda Istabl",
				"Saghbine",
				"Sohmor",
				"Souairi",
				"Soultan Yaaqoub Aradi",
				"Soultane Yaaqoub el Faouqa",
				"Soultane Yaaqoub el Tahta",
				"Tall ez Zaazeaa",
				"Tall Znoub",
				"Tall Znoub ej Jdide",
				"Yohmor West Bekaa",
				"Zellaya",
			],
			citiesAr: [
				"عميق",
				"عانا",
				"عين التينة بقاع الغربي",
				"عين زبدة",
				"عيتنيت",
				"الوقف بقاع الغربي",
				"بعلول",
				"باب مارع",
				"شبرقية عميق",
				"دكوة",
				"دير عين الجوزة",
				"دير طحنيش",
				"الجزيرة",
				"المرج",
				"غزة",
				"حمارة",
				"حريمة الصغرى",
				"حوش عميق",
				"حوش الحريمة",
				"حوش السعلوك",
				"جب جنين",
				"كفريا بقاع الغربي",
				"كامد اللوز",
				"الخيارة",
				"خيارة العتيقة",
				"خربة قنافار",
				"لالا",
				"لبايا",
				"لوسيا",
				"مشغرة",
				"المنصورة",
				"ميدون",
				"نبع الخريزات",
				"القرعون",
				"قلايا",
				"روضة إسطبل",
				"صغبين",
				"سحمر",
				"صويري",
				"سلطان يعقوب أراضي",
				"سلطان يعقوب الفوقا",
				"سلطان يعقوب التحتا",
				"تل الزعزع",
				"تل زنوب",
				"تل زنوب جديدة",
				"يحمر بقاع الغربي",
				"زلايا",
			],
		},
		{
			districtEn: "Bekaa - Rashaya",
			districtAr: "البقاع - راشيا",

			citiesEn: [
				"Aaiha",
				"Aaqbe",
				"Aaz el Aarab",
				"Ain Aarab",
				"Ain Aata",
				"Ain Hircha",
				"Aita el Foukhar",
				"Bakka",
				"Bakkifa",
				"Bayader el Aadas",
				"Beit Lahia",
				"Bire rachaya",
				"Dahr el Ahmar",
				"Deir el Aachayer",
				"El Faqaa",
				"En Nabi Safa",
				"Haloua",
				"Haouch El Qinnabeh",
				"Haret el Kaouasbe",
				"Jebb Farah",
				"Kaoukaba",
				"Kfar Danis",
				"Kfar Mechki",
				"Kfar Qouq",
				"Khirbet Rouha",
				"Majdal Balhis",
				"Marj es Simah",
				"Mazraat Aazzi",
				"Mazraat Ain Qeniye",
				"Mazraat Deir el Aachaiyer",
				"Mazraat el Qalioun",
				"Mazraat Jaafar",
				"Mazret Al Chmis",
				"Mdoukha",
				"Mhaidse",
				"Qnaabe",
				"Rachaiya",
				"Rafid",
				"Selsata Mazraat Dier el Aachayer",
				"Tannoura",
				"Yanta",
			],
			citiesAr: [
				"عيحا",
				"عقبة راشيّا",
				"عز العرب",
				"عين عرب",
				"عين عطا",
				"عين حرشة",
				"عيتا الفخار",
				"بكا",
				"بكيفا راشيا",
				"بيادر العدس",
				"بيت لهيا",
				"بيرة راشّيا",
				"ضهر الاحمر",
				"دير العشاير",
				"الفقعة",
				"نبي صفا",
				"حلوة",
				"حوش القنعبة",
				"حارة الكواسبة",
				"جب فرح",
				"كوكبا",
				"كفر دنيس",
				"كفر مشكي",
				"كفرقوق",
				"خربة روحا",
				"مجدل بلهيص",
				"مرج السماح",
				"مزرعة عزِي",
				"مزرعة عين قنية",
				"مزرعة دير العشاير",
				"مزرعة القليون",
				"مزرعة جعفر",
				"مزرعة الشميسة",
				"مدوخا",
				"محيدثه",
				"قنعبة",
				"راشيّا الوادي",
				"الرافد راشيا",
				"مزرعة سلساتا",
				"تنورة",
				"ينطا",
			],
		},
		{
			districtEn: "Bekaa - Baalbek El Hermel",
			districtAr: "البقاع - بعلبك الهرمل",

			citiesEn: [
				"Aadous",
				"Aallaq",
				"Aamchki",
				"Aarsal",
				"Aayoun Orghoush",
				"Ain Bourday",
				"Ain Ej Jaouze",
				"Ain El Bnaiye",
				"Ain es Saouda",
				"Ainata",
				"Al Ansar Baalbek",
				"Baalbek",
				"Baayoun",
				"Barqa",
				"Bechouat",
				"Bednayel",
				"Beit Chama",
				"Beit es Satiti",
				"Beit Habchi",
				"Beit Mchik",
				"Bejjaje",
				"Betdaai",
				"Blaiqa",
				"Boudai",
				"Britel",
				"Bsayleh al Fawka",
				"Bsayleh al Tahta",
				"Chaat",
				"Chlifa",
				"Chmistar",
				"Daouret en Naml",
				"Dar el Ouassaa",
				"Deir El Ahmar",
				"Deir Mar Maroun Baalbek",
				"Douris",
				"El Aaiara",
				"El Ain",
				"El Barake",
				"El Faqrat",
				"El Laouze",
				"El Maalqa",
				"El Marmagha",
				"El Qaa",
				"El Qerrami",
				"En Nouqra",
				"Fakehe",
				"Flaoui",
				"Freij",
				"Hadet Hermel",
				"Hai el Mathane",
				"Halbata",
				"Ham",
				"Haouch Barada",
				"Haouch Ed Dahab",
				"Haouch En Nabi",
				"Haouch Snaid",
				"Haouch Tall Safiye",
				"Haouerte",
				"Haour Taala",
				"Harabta",
				"Harfouch",
				"Hfayer",
				"Hizzine",
				"Hosn ech Chadoura",
				"Houch Er Rafqa",
				"Iaat",
				"Jabaa",
				"Jabal Ech Chaaibe",
				"Jabboule",
				"Janta",
				"Jdaide Fekehe",
				"Joubaniyeh",
				"Kfar Dabach",
				"Kfar Dane",
				"Kharayeb",
				"Khermateh",
				"Khirbet Daoud Baalbek",
				"Khirbet et Tine",
				"Khirbet Haouerte",
				"Khirbet Younine",
				"Khodor",
				"Khraibe",
				"Knaisse",
				"Laboue",
				"Maarboun",
				"Mahatta",
				"Majdaloun",
				"Maql el Bouadte",
				"Maqne",
				"Masnaa",
				"Masnaa es Zohr",
				"Mathanet Mousrayeh",
				"Mazraat al Ramassy",
				"Mazraat Al Souaydane",
				"Mazraat al Takch",
				"Mazraat Beit el Ghoussain",
				"Mazraat Beit Slaibi",
				"Mazraat Ed Dallil",
				"Mazraat ed Dhour",
				"Mazraat Es Saiyed",
				"Mazraat Matar",
				"Mazraat Oumm Aali",
				"Mchaitiye",
				"Mehairfe",
				"Mhattat Ras Baalbeck",
				"Mkaybel Al Kala'",
				"Moqraq",
				"Mrah Beit Aassaf",
				"Mrah Beit el Qazah",
				"Mrah Beit Slim",
				"Mrah Bou Brahim",
				"Mrah Bou Chahine",
				"Mrah ech Chmis",
				"Mrah ech Choaab",
				"Mrah ej Jamal",
				"Mrah ej Jeddaoui",
				"Mrah El Aabed",
				"Mrah El Aaouja",
				"Mrah El Aassi",
				"Mrah el Ahmar",
				"Mrah el Blata",
				"Mrah EL Harfouch",
				"Mrah es Sirghane",
				"Mrah Haissoun",
				"Mrah Kloude",
				"Mrah Najib",
				"Mrah Rafi",
				"Mrah Semaan",
				"Mrah Soukkar",
				"Nabha",
				"Nabha Al Mohfara",
				"Nabi Chit",
				"Nabi Osmane",
				"Nabi Rachade",
				"Nabi Sbat",
				"Nahle",
				"Qaa Jouar Maqiyeh",
				"Qaa Ouadi el Khanzir",
				"Qalaat Bakdach",
				"Qalb es Sabaa",
				"Qarha",
				"Qiddam",
				"Qlaile",
				"Qsarnaba",
				"Ram",
				"Ras al Assy",
				"Ras Baalbek",
				"Ras Baalbek ech Charqi",
				"Ras Baalbek es Sahel",
				"Rasm El Hadet",
				"Riha",
				"Saaide",
				"Safra",
				"Saidet ed Dalil",
				"Saraain el Faouqa",
				"Saraain et Tahta",
				"Sbouba",
				"Sifri",
				"Siret Hanna",
				"Slouqi",
				"Taibe Baalbek",
				"Talia",
				"Tall Sougha",
				"Tallet ed Deir",
				"Tammine et Tahta",
				"Tamnine El Faouqa",
				"Taraiya",
				"Tfail",
				"Toufiqiye",
				"Wadi el Assouad",
				"Wadi el Oss",
				"Yahfoufa",
				"Yammoune",
				"Younine",
				"Zabboud",
				"Zarayeb",
				"Zarayeb Choukr",
				"Zeribet es Sabha",
				"Zrazir",
				"Aaqabe",
				"Ain al Jadideh",
				"Ain el bayda",
				"Bdita",
				"Beit Aallam",
				"Beit Aallaou",
				"Beit es Semmaqa",
				"Beit Hira",
				"Berghoch",
				"Biyout Aawad",
				"Biyout el Ain",
				"Biyout el Hajj Hassan",
				"Biyout er Rouais",
				"Biyout es Souh",
				"Bou Sawaya",
				"Bouaida",
				"Boustane",
				"Breij",
				"Brissa",
				"Charbine",
				"Chouaghir",
				"Ed Daoura el hermel",
				"El Baaoul",
				"El Mdawesh",
				"El Ouaqf",
				"El Qraita",
				"Es Souaidiye",
				"Faara",
				"Fissane",
				"Haouch Es Saiyad Aali",
				"Haouchariye",
				"Haret El Maasser",
				"Hariqa el hermel",
				"Hawch Beit Ismail",
				"Hermel",
				"Hermel Jbab",
				"Hmaire",
				"Jawz",
				"Jisr el Aassi",
				"Jouar El Hachich",
				"Jouret el Mzar",
				"Kouakh",
				"Maaisr",
				"Mansoureh",
				"Marj Hine",
				"Mazraat Beit el Fqih",
				"Mazraat Beit Et Tachm",
				"Mazraat Et Talle",
				"Mnaira",
				"Mrah Aabbas",
				"Mrah Beit Aalaoui",
				"Mrah Bou Kamar al Dine",
				"Mrah Ech Chaab",
				"Mrah ech Charqi",
				"Mrah ech Chnain",
				"Mrah el Aaqabe",
				"Mrah El Ain",
				"Mrah el Arab",
				"Mrah El Dalil",
				"Mrah el Gharbi",
				"Mrah el Mahlise",
				"Mrah El Mouchref",
				"Mrah El Mougher",
				"Mrah el Qorne",
				"Mrah el Qraita",
				"Mrah es Siyaid",
				"Mrah esh Shmis",
				"Mrah Ez Zakbe",
				"Mrah Houssain Taane",
				"Mrah Naaouas",
				"Mrah Sejoud",
				"Mrah Yassine",
				"Nasriye",
				"Ouadi en Nayra",
				"Ouadi Er Ratle",
				"Ouadi et Tourkmane",
				"Qanafez",
				"Qasr",
				"Quadi el Karm",
				"Ras Baalbek el Gharbi",
				"Ras Baalbek Ouadi Faara",
				"Salhat El Ma",
				"Sharbine el Faouqa",
				"Souaisse",
				"Tall El far",
				"Wadi Bnit",
				"Wadi Faara",
				"Zighrine",
				"Zighrine Et Tahta",
				"Zouaitini Zighrine",
			],
			citiesAr: [
				"عدّوس",
				"علاق",
				"عمشكي",
				"عرسال",
				"عيون ارغش",
				"عين بورداي",
				"عين الجوزة",
				"عين البنية",
				"عين السودا",
				"عيناتا",
				"الأنصار بعلبك",
				"بعلبك",
				"قاع بعيون",
				"برقا",
				"بشوات",
				"بدنايل",
				"بيت شاما",
				"بيت الستيته",
				"بيت حبشي",
				"مزرعة بيت مشيك",
				"بجاجة",
				"بتدعي",
				"بليقة",
				"بوداي",
				"بريتال",
				"بصيلة الفوقا",
				"بصيلة التحتا",
				"شعت",
				"شليفا",
				"شمسطار",
				"دورة النمل",
				"دار الواسعة",
				"دير الاحمر",
				"دير مار مارون بعلبك",
				"دوريس",
				"عيارة",
				"العين",
				"البركة",
				"فقرات",
				"اللوزة",
				"معلقة الجديدة",
				"مرماغا",
				"القاع",
				"قرامي",
				"نقرة",
				"فاكهة",
				"فلاوي",
				"فريج",
				"حدت الهرمل",
				"حي المطحنة",
				"حلباتا",
				"حام",
				"حوش بردى",
				"حوش الدهب",
				"حوش النبي",
				"حوش سنيد",
				"حوش تل صفية",
				"حوارته",
				"حور تعلا",
				"حربتا",
				"حرفوش",
				"حفاير",
				"حزين",
				"حصن الشادورا",
				"حوش الرافقة",
				"ايعات",
				"جعبعا",
				"جبل الشعيبة",
				"جبولة",
				"جنتا",
				"جديدة الفاكهة",
				"جوبانية",
				"كفر دبش",
				"كفر دان",
				"الخرائب",
				"خورماتا",
				"خربة داوود بعلبك",
				"خربة التينه",
				"خربة حوارته",
				"خربة يونين",
				"خضر",
				"خريبة",
				"كنيسة",
				"لبوة",
				"معربون",
				"المحطة",
				"مجدلون",
				"مقل البوادتي",
				"مقنة",
				"المصنع",
				"مصنع الزهر",
				"مطحنة مصراية",
				"مزرعة الرماسا",
				"مزرعة آل سويدان",
				"مزرعة بيت طقش",
				"مزرعة بيت الغصين",
				"مزرعة بيت صليبي",
				"مزرعة الضليل",
				"مزرعة الضهور",
				"مزرعة السيد",
				"مزرعة مطر",
				"مزرعة ام علي",
				"مشيتية",
				"محيرفة",
				"المحطة راس بعلبك",
				"مقيال القلعة",
				"المقرق",
				"مراح بيت عساف",
				"مراح بيت القزح",
				"مراح بيت سليم",
				"مراح بو براهيم",
				"مراح بو شاهين",
				"مراح الشميس",
				"مراح الشعاب",
				"مراح",
				"مراح الجداوي",
				"مراه العبد",
				"مراح العوجا",
				"مراح العاصي",
				"مراح الاحمر",
				"مراح البلاطة",
				"مراح الحرفوش",
				"مراح السرغانه",
				"مراح حيصون",
				"مراح القلود",
				"مراح نجيب",
				"مراح رافي",
				"مراح سمعان",
				"مراح سكر",
				"نبحا",
				"نبحا المحفارة",
				"نبي شيت",
				"نبي عثمان",
				"نبي رشاده",
				"النبي سباط",
				"نحله",
				"قاع جوار مكية",
				"قاع وادي الخنزير",
				"قلعة بكداش",
				"مزرعة قلد السبع",
				"قرحا",
				"القدام",
				"قليلة",
				"قصرنابا",
				"الرام",
				"راس العاصي",
				"راس بعلبك",
				"راس بعلبك الشرقي",
				"راس بعلبك السهل",
				"رسم الحدث",
				"ريحا",
				"سعيدة",
				"صفرا",
				"سيدة الضليل",
				"سرعين الفوقا",
				"سرعين التحتا",
				"صبوبا",
				"سفري",
				"سيرة هنا",
				"سلوقي",
				"طيبة بعلبك",
				"طليا",
				"تل سغى",
				"تلة الدير",
				"تمنين التحتا",
				"تمنين الفوقا",
				"طاريا",
				"طفيل",
				"التوفيقية",
				"وادي الاسود",
				"وادي القصص",
				"يحفوفا",
				"يمونة",
				"يونين",
				"زبود",
				"زرايب",
				"زرايب شكر",
				"زريبة الصبحا",
				"زرازير",
				"عقبة",
				"عين الجديدة الهرمل",
				"عين البيضاء",
				"بديتا",
				"بيت علام",
				"بيت علاّو",
				"بيت السماقة",
				"بيت حيرا",
				"برغش",
				"بيوت عواد",
				"بيوت العين",
				"بيوت الحاج حسن",
				"بيوت الرويس",
				"بيوت السوح",
				"بو صوايا",
				"بويضة",
				"بستان",
				"البريج",
				"بريصا",
				"شربين",
				"شواغير",
				"الدورة الهرمل",
				"البعول",
				"مداوش",
				"الوقف",
				"قريتي",
				"سويدية",
				"فعرا",
				"فيسان",
				"حوش السيد علي",
				"هوشرية",
				"حارة المعاصر",
				"حريقة الهرمل",
				"حوش بيت اسماعيل",
				"هرمل",
				"هرمل جباب",
				"حميرة",
				"جوز",
				"جسر العاصي",
				"جوار الحشيش",
				"جورة المزار",
				"كواخ",
				"معيصرة",
				"منصورة",
				"مرجحين",
				"مزرعة بيت الفقيه",
				"مزرعة بيت الطشم",
				"مراح التلة",
				"منيرة",
				"مراح عباس",
				"مراح بيت علاو",
				"مراح بو قمر الدين",
				"مراح الشعاب الهرمل",
				"مراح الشرقي",
				"مراح شنين",
				"مراح العقبة",
				"مراح العين",
				"مراح العرب",
				"مراح الدليل",
				"مراح الغربي",
				"مراح المحليسة",
				"مراح المشرف",
				"مراح المغر",
				"مراح القرنة",
				"مراح القريتا",
				"مراح السياد",
				"مراح الشميس الهرمل",
				"مراح الزكبة",
				"مراح حسين طعان",
				"مراح النواس",
				"مراح سجد",
				"مراح ياسين",
				"ناصرية الهرمل",
				"وادي النيرة",
				"وادي الرطل",
				"وادي التركمان",
				"قنافذ",
				"القصر",
				"وادي الكرم",
				"راس بعلبك الغربي",
				"راس بعلبك وادي فعرا",
				"سهلات المي",
				"شربين الفوقا",
				"السويسة",
				"تل الفار",
				"وادي بنيت",
				"وادي فعرا",
				"زغرين",
				"زغرين التحتى",
				"الزويتينه زغرين",
			],
		},
		{
			districtEn: "Nabatieh",
			districtAr: "النبطية",

			citiesEn: [
				"Aainata",
				"Aaitaroun",
				"Aayta ej Jabal Zott",
				"Ain Ebel",
				"Aita Ech Chaab",
				"Beit Lif",
				"Beit Yahnoun",
				"Bent Jubail",
				"Bir es Sanassel",
				"Borj Qalaouiye",
				"Braachit",
				"Chaqra",
				"Debl Oummiya",
				"Deir Ntar",
				"Doubiye",
				"El Birke",
				"El Biyad",
				"Froun",
				"Ghandouriye Bent Jbeil",
				"Haddatha",
				"Hanine",
				"Hariss",
				"Hay el Jameaa",
				"Jmaijime",
				"Kafra Bent Jbeil",
				"Kfar Dounine",
				"Khirbit Silim",
				"Kounine",
				"Maroun er Ras",
				"Mazraat Aazze",
				"Qalaouiye",
				"Qaouzah",
				"Qatmoun",
				"Rachaf",
				"Ramiye",
				"Rmaich",
				"Safad el Battikh",
				"Salhani",
				"Soultaniye",
				"Sribbine",
				"Taire",
				"Tebnine",
				"Yaroun",
				"Yater",
				"Aabba",
				"Aadchit ech Chqif",
				"Aali et Taher",
				"Aarnoun",
				"Aazze",
				"Ain Qana",
				"Arab Salim",
				"Braiqaa",
				"Charqiye",
				"Choukine",
				"Deir ez Zahrani",
				"Doueir El Nabatieh",
				"El Aaqide",
				"El Bayad",
				"El Midane",
				"Es Serail",
				"Habbouch",
				"Hamra  En-Nabattiyeh",
				"Harouf",
				"Hima Aarnoun",
				"Hmaile",
				"Houmine el Faouqa",
				"Houmine et Tahta",
				"Insar",
				"Jaouhariye",
				"Jarjouaa",
				"Jbaa El Nabatieh",
				"Jibchit",
				"Kafra",
				"Kfar Dajjal",
				"Kfar Fila",
				"Kfar Roummane",
				"Kfar Sir",
				"Kfar Tebnit",
				"Kfaroue",
				"Kfour El Nabatieh",
				"Maifadoun",
				"Manzleh",
				"Mazraat Ain Bou Souar",
				"Mazraat Bsafour",
				"Mazraat Chelbael",
				"Mazraat Dmoul",
				"Mazraat el Baiyad",
				"Mazraat el Khraibe",
				"Mazraat Kfar ej Jouz",
				"Mazraat Maqsam Aali et Taher",
				"Mazraat Qalaat Meis",
				"Nabatiye el Faouqa",
				"Nabatiye el Tahta",
				"Nmairiye",
				"Qaaqaait ej Jisr",
				"Qsaibe El Nabatieh",
				"Roumine",
				"Sarba El Nabatieh",
				"Sir el Gharbiye",
				"Toul",
				"Yohmor",
				"Zaoutar ech Charqiye",
				"Zaoutar el Gharbiye",
				"Zebdine El Nabatieh",
				"Zefta",
				"Abou Qamha",
				"Ain Jerfa",
				"Ain Qenya",
				"Ain Tanta",
				"Ayn et Tine",
				"Bathaniye",
				"Berghoz",
				"Chebaa",
				"Chouaia",
				"Dehayrjate",
				"Dellafi",
				"El Majidiye",
				"Fardis",
				"Fashkoul",
				"Halta Hasbaya",
				"Hasbaiya",
				"Hebbariye",
				"Kaoukaba Hasbaya",
				"Kfair",
				"Kfar Chouba",
				"Kfar Hamam",
				"Khallet el Ghazale",
				"Khalouat el Biyada",
				"Khalouat Hasbaya",
				"Khirbet ed Dwayr",
				"Khraibe Hasbaya",
				"Mari",
				"Marj Ez Zouhour Dnaibe",
				"Mazraat Qafoua",
				"Mazraat Ras el Baidar",
				"Mimes",
				"Ouazzani",
				"Rachaiya el Foukhar",
				"Slaiyeb",
				"Tallet el Qaaqour",
				"Zaghla",
				"Aadaisse",
				"Aadchit el Qoussair",
				"Aalmane",
				"Aamra",
				"Aarab el Louaize",
				"Ain Aarab Marjaayoun",
				"Baiyouda",
				"Beni Haiyane",
				"Blat Marjaayoun",
				"Blida",
				"Borj El Mlouk",
				"Deir Mimas",
				"Deir Siriane",
				"Dibbine",
				"Houla",
				"Houra",
				"Ibl es Saqi",
				"Jlali el Ghozlane",
				"Kfar Kila",
				"Khiam",
				"Khirbe",
				"MAZRAAT ZAIYEH",
				"Maissate",
				"Majdel Silim",
				"Marjaayoun",
				"Markaba",
				"Mazraat Doumiat",
				"Mazraat ej Jreine",
				"Mazraat Sahsahiye",
				"Meiss ej Jabal",
				"Mhaibib",
				"Qabrikha",
				"Qalaat Doubai",
				"Qantara",
				"Qlaiaa",
				"Qsair",
				"Rabb et Talatine",
				"Sarda",
				"Serail",
				"Souane Marjaayoun",
				"Taibe Marjaayoun",
				"Tallouse",
				"Touline",
			],
			citiesAr: [
				"عيناتا بنت جبيل",
				"عيترون",
				"عيتا الجبل الزط",
				"عين ابل",
				"عيتا الشعب",
				"بيت ليف",
				"بيت ياحون",
				"بنت جبيل",
				"بير السناسل",
				"برج قلويه",
				"برعشيت",
				"شقرا",
				"دبل امية",
				"دير نطار",
				"دوبية",
				"البركه بنت جبيل",
				"البياد",
				"فرون",
				"غندورية بنت جبيل",
				"حداثا",
				"حنين",
				"حاريص",
				"الجامع بنت جبيل",
				"جميجمة",
				"كفرا بنت جبيل",
				"كفر دونين",
				"خربة سلم",
				"كونين",
				"مارون الراس",
				"مزرعة عزه",
				"قلويه",
				"قوزح",
				"قطموم",
				"رشف",
				"رامية بنت جبيل",
				"رميش",
				"صفد البطيخ",
				"الصلحاني",
				"سلطانية",
				"صربين",
				"طيري",
				"تبنين",
				"يارون",
				"ياطر",
				"عبا",
				"عدشيت الشقيف",
				"علي الطاهر",
				"أرنون",
				"عزه",
				"عين قانا",
				"عرب صاليم",
				"بريقع",
				"شرقية",
				"شوكين",
				"دير الزهراني",
				"الدوير النبطية",
				"عقيدة",
				"نبطية البياض",
				"الميدان",
				"السراي",
				"حبوش",
				"الحمرا النبطية",
				"حروف",
				"حمى أرنون",
				"حميلة",
				"حومين الفوقا",
				"حومين التحتا",
				"إنصار",
				"جوهرية",
				"جرجوع",
				"جباع النبطية",
				"جبشيت",
				"كفرا",
				"كفردجال",
				"كفرفيلا",
				"كفر رمان",
				"كفرصير",
				"كفر تبنيت",
				"كفروة أو بفروة",
				"الكفور النبطية",
				"ميفدون",
				"المنزلة",
				"مزرعة عين بوسوار",
				"مزرعة بصفُور",
				"مزرعة شلبعل",
				"مزرعة دمول",
				"مزرعة البياض",
				"مزرعة الخريبة",
				"مزرعة كفر جوز",
				"مزرعة علي الطاهر",
				"مزرعة قلعة ميس",
				"نبطية الفوقا",
				"نبطية التحتا",
				"نميرية",
				"قعقعية الجسر",
				"قصيبة النبطية",
				"رومين",
				"صربا النبطية",
				"صير الغربية",
				"تول",
				"يحمر",
				"زوطر الشرقية",
				"زوطر الغربية",
				"زبدين النبطية",
				"زفتا",
				"أبو قمحة",
				"عين جرفا",
				"عين قنيا",
				"عين تنتا حاصبيا",
				"عين التينة حاصبيا",
				"بيتسنيا",
				"برغز",
				"شبعا",
				"شويّا",
				"الدحيرجات",
				"دلافة",
				"مجيدية حاصبيا",
				"الفرديس",
				"فشكول",
				"حلتا حاصبيّا",
				"حاصبيّا",
				"هبّارية",
				"كوكبا حاصبيّا",
				"كفير الزيت",
				"كفر شوبا",
				"كفرحمام",
				"خلة الغزالة",
				"خلوات البياضة",
				"خلوات حاصبيّا",
				"خربة الدوير",
				"خريبة حاصبيّا",
				"ماري",
				"مرج الزهور الدنيبة",
				"مزرعة قفوى",
				"مزرعة راس البيدر",
				"ميمس",
				"وزاني",
				"راشيّا الفخار",
				"صلايب",
				"تلة القعقور",
				"زغلة",
				"عديسة مرجعيون",
				"عدشيت القصير",
				"علمانة",
				"عمرة",
				"عرب اللويزة",
				"عين عرب مرجعيون",
				"بويضة مرجعيون",
				"بني حيان",
				"بلاط مرجعيون",
				"بليدا",
				"برج الملوك",
				"دير ميماس",
				"دير سريان",
				"دبين",
				"حولا",
				"حوره",
				"إبل السقي",
				"جلال الغزلان",
				"كفركيلا",
				"الخيام",
				"خربة برج الملوك",
				"مزرعة زئية",
				"الميسات",
				"مجدل سلم",
				"مرجعيون",
				"مركبا",
				"مزرعة دمياط",
				"مزرعة الجرين",
				"مزرعة السهسهية",
				"ميس الجبل",
				"محيبيب",
				"قبريخا",
				"قلعة دبي",
				"قنطرة",
				"قليعة",
				"قصير",
				"رب التلاتين",
				"مزرعة  سردة",
				"سراي",
				"صوانة مرجعيون",
				"طيبة مرجعيون",
				"طلوسة",
				"تولين",
			],
		},
	];

	const seedData = districts.map((district) => ({
		district: { en: district.districtEn, ar: district.districtAr },
		cities: district.citiesEn
			.map((cityEn, index) => ({
				en: cityEn,
				ar: district.citiesAr[index],
			}))
			.filter((city) => city.ar),
	}));

	await Location.insertMany(seedData);
	console.log("Locations seeded successfully");
}

export default seedLocations;
